package com.maju.desarrollo.testfcs.SQLite.Model;

public class DCPower {
    String ID_fORMATO;
    String GRAL_FOLIO_PRETRABAJO;
    String GRAL_CLIENTE;
    String GRAL_DIRECCION;
    String GRAL_CONTACTO;
    String GRAL_TELEFONO;
    String GRAL_MAIL;
    String GRAL_PROYECTO;
    String GRAL_REFERENCIA;
    String GRAL_SR;
    String GRAL_TASK;
    String GRAL_TIPO_SERVICIO;
    String GRAL_ESPECIFICACION;
    String GRAL_FRECUENCIA;
    String GRAL_NTAG;
    String GRAL_MODELO;
    String GRAL_SERIE;
    String GRAL_SERIE2;
    String GRAL_FECHA_INICIO;
    String GRAL_FECHA_FIN;
    String PARAM_GRALS_TIPO;
    String PARAM_GRALS_N_ESPECIFICAION;
    String PARAM_GRALS_CAPACIDAD;
    String PARAM_GRALS_CONFIGURACION;
    String PARAM_GRALS_CARGA_ACT;
    String PARAM_INV_RECTIFICADORES_MODELO;
    String PARAM_INV_RECTIFICADORES_N_ESPECIFICACION;
    String PARAM_INV_RECTIFICADORES_CAPACIDAD;
    String PARAM_INV_RECTIFICADORES_R1;
    String PARAM_INV_RECTIFICADORES_R2;
    String PARAM_INV_RECTIFICADORES_R3;
    String PARAM_INV_RECTIFICADORES_R4;
    String PARAM_INV_RECTIFICADORES_R5;
    String PARAM_INV_RECTIFICADORES_R6;
    String PARAM_INV_RECTIFICADORES_R7;
    String PARAM_INV_RECTIFICADORES_R8;
    String PARAM_INV_RECTIFICADORES_R9;
    String PARAM_INV_RECTIFICADORES_R10;
    String PARAM_INV_RECTIFICADORES_R11;
    String PARAM_INV_RECTIFICADORES_R12;
    String PARAM_INV_RECTIFICADORES_R13;
    String PARAM_INV_RECTIFICADORES_R14;
    String PARAM_INV_RECTIFICADORES_R15;
    String PARAM_INV_RECTIFICADORES_R16;
    String PARAM_INV_RECTIFICADORES_R17;
    String PARAM_INV_RECTIFICADORES_R18;
    String PARAM_INV_RECTIFICADORES_R19;
    String PARAM_INV_RECTIFICADORES_R20;
    String PARAM_INV_RECTIFICADORES_R21;
    String PARAM_INV_RECTIFICADORES_R22;
    String PARAM_INV_RECTIFICADORES_R23;
    String PARAM_INV_RECTIFICADORES_R24;
    String PARAM_INV_RECTIFICADORES_R25;
    String PARAM_INV_RECTIFICADORES_R26;
    String PARAM_INV_RECTIFICADORES_R27;
    String PARAM_INV_RECTIFICADORES_R28;
    String PARAM_INV_RECTIFICADORES_R29;
    String PARAM_INV_RECTIFICADORES_R30;
    String PARAM_INV_RECTIFICADORES_R31;
    String PARAM_INV_RECTIFICADORES_R32;
    String PARAM_INV_GABINETES_NA;
    String PARAM_INV_GABINETES_ESPECIFIC;
    String PARAM_INV_GABINETES_GAB1;
    String PARAM_INV_GABINETES_GAB2;
    String PARAM_INV_GABINETES_GAB3;
    String PARAM_INV_GABINETES_GAB4;
    String PARAM_INV_GABINETES_GAB5;
    String PARAM_INV_GABINETES_GAB6;
    String PARAM_SUPRESOR_NA;
    String PARAM_SUPRESOR_MARCA;
    String PARAM_SUPRESOR_MODELO;
    String PARAM_SUPRESOR_INSTALAC;
    String PARAM_SUPRESOR_CALIBRE_CONEXION;
    String PARAM_SUPRESOR_CAPACIDAD;
    String PARAM_SUPRESOR_CALIBRE_TIERRAS;
    String PARAM_AyO_PLANTA_ALIMENT_M1;
    String PARAM_AyO_PLANTA_ALIMENT_M2;
    String PARAM_AyO_PLANTA_ALIMENT_M3;
    String PARAM_AyO_PLANTA_ALIMENT_M4;
    String PARAM_AyO_PLANTA_ALIMENT_M5;
    String PARAM_AyO_PLANTA_ALIMENT_M6;
    String PARAM_AyO_PLANTA_ALIMENT_M7;
    String PARAM_AyO_PLANTA_ALIMENT_M8;
    String PARAM_AyO_PLANTA_OPERAC_M1;
    String PARAM_AyO_PLANTA_OPERAC_M2;
    String PARAM_AyO_PLANTA_OPERAC_M3;
    String PARAM_AyO_PLANTA_OPERAC_M4;
    String PARAM_AyO_PLANTA_OPERAC_M5;
    String PARAM_AyO_PLANTA_OPERAC_M6;
    String PARAM_AyO_PLANTA_OPERAC_M7;
    String PARAM_AyO_PLANTA_OPERAC_M8;
    String PARAM_AyO_PLANTA_OPERAC_M9;
    String PARAM_AyO_PLANTA_OPERAC_M10;
    String PARAM_AyO_PLANTA_LIMPIEZA_INTERNA;
    String PARAM_AyO_PLANTA_LIMPIEZA_INDV;
    String PARAM_AyO_PLANTA_VERIFICAION;
    String PARAM_STPF_DC_NA;
    String PARAM_STPF_DC_CAMP1;
    String PARAM_STPF_DC_CAMP2;
    String PARAM_STPF_DC_CAMP3;
    String PARAM_STPF_DC_CAMP4;
    String PARAM_STPF_DC_CAMP5;
    String PARAM_STPF_DC_CAMP6;
    String PARAM_STPF_DC_CAMP7;
    String PARAM_STPF_DC_CAMP8;
    String PARAM_ITPF_DC_NA;
    String PARAM_ITPF_DC_CAMP1;
    String PARAM_ITPF_DC_CAMP2;
    String PARAM_ITPF_DC_CAMP3;
    String PARAM_ITPF_DC_CAMP4;
    String PARAM_ITPF_DC_CAMP5;
    String PARAM_ITPF_DC_CAMP6;
    String PARAM_ITPF_DC_CAMP7;
    String PARAM_SISTEMA_DIST_NA;
    String PARAM_SISTEMA_DIST_MODELO;
    String PARAM_SISTEMA_DIST_MARCA;
    String PARAM_SISTEMA_DIST_ESPECIFI;
    String PARAM_SISTEMA_DIST_CAPACIDAD;
    String PARAM_SISTEMA_DIST_CONFIGURACION;
    String PARAM_IDR_NA;
    String PARAM_IDR_CAMP1;
    String PARAM_IDR_CAMP2;
    String PARAM_IDR_CAMP3;
    String PARAM_IDR_CAMP4;
    String PARAM_IDR_CAMP5;
    String PARAM_IDR_CAMP6;
    String PARAM_IDR_CAMP7;
    String PARAM_IDR_BREAK1;
    String PARAM_IDR_BREAK2;
    String PARAM_IDR_BREAK3;
    String PARAM_IDR_BREAK4;
    String PARAM_IDR_BREAK5;
    String PARAM_IDR_BREAK6;
    String PARAM_IDR_BREAK7;
    String PARAM_IDR_BREAK8;
    String PARAM_SISTEMA_INVER_NA;
    String PARAM_SISTEMA_INVER_MODELO;
    String PARAM_SISTEMA_INVER_MARCA;
    String PARAM_SISTEMA_INVER_ESPEC;
    String PARAM_SISTEMA_INVER_CAPACIDAD;
    String PARAM_SISTEMA_INVER_CONFG;
    String PARAM_SISTEMA_INVER_A_PIEZA;
    String PARAM_SISTEMA_INVER_A_INV1;
    String PARAM_SISTEMA_INVER_A_INV2;
    String PARAM_SISTEMA_INVER_A_INV3;
    String PARAM_SISTEMA_INVER_A_INV4;
    String PARAM_SISTEMA_INVER_A_INV5;
    String PARAM_SISTEMA_INVER_A_INV6;
    String PARAM_SISTEMA_INVER_A_INV7;
    String PARAM_SISTEMA_INVER_A_INV8;
    String PARAM_SISTEMA_INVER_A_INV9;
    String PARAM_SISTEMA_INVER_A_INV10;
    String PARAM_SISTEMA_INVER_B_PIEZA;
    String PARAM_SISTEMA_INVER_B_INV1;
    String PARAM_SISTEMA_INVER_B_INV2;
    String PARAM_SISTEMA_INVER_B_INV3;
    String PARAM_SISTEMA_INVER_B_INV4;
    String PARAM_SISTEMA_INVER_B_INV5;
    String PARAM_SISTEMA_INVER_B_INV6;
    String PARAM_SISTEMA_INVER_B_INV7;
    String PARAM_SISTEMA_INVER_B_INV8;
    String PARAM_SISTEMA_INVER_B_INV9;
    String PARAM_SISTEMA_INVER_B_INV10;
    String PARAM_SISTEMA_INVER_C_PIEZA;
    String PARAM_SISTEMA_INVER_C_INV1;
    String PARAM_SISTEMA_INVER_C_INV2;
    String PARAM_SISTEMA_INVER_C_INV3;
    String PARAM_SISTEMA_INVER_C_INV4;
    String PARAM_SISTEMA_INVER_C_INV5;
    String PARAM_SISTEMA_INVER_C_INV6;
    String PARAM_SISTEMA_INVER_C_INV7;
    String PARAM_SISTEMA_INVER_C_INV8;
    String PARAM_SISTEMA_INVER_C_INV9;
    String PARAM_SISTEMA_INVER_C_INV10;
    String PARAM_SISTEMA_INVER_VERI1;
    String PARAM_SISTEMA_INVER_VERI2;
    String PARAM_SISTEMA_INVER_VERI3;
    String PARAM_SISTEMA_INVER_VERI4;
    String PARAM_SISTEMA_INVER_LIMP;
    String PARAM_NAyS_ALIM_VAC1;
    String PARAM_NAyS_ALIM_VAC2;
    String PARAM_NAyS_ALIM_VAC3;
    String PARAM_NAyS_ALIM_VAC4;
    String PARAM_NAyS_ALIM_VAC5;
    String PARAM_NAyS_ALIM_VAC6;
    String PARAM_NAyS_ALIM_VAC7;
    String PARAM_NAyS_ALIM_VAC8;
    String PARAM_NAyS_ALIM_ACA1;
    String PARAM_NAyS_ALIM_ACA2;
    String PARAM_NAyS_ALIM_ACA3;
    String PARAM_NAyS_ALIM_ACA4;
    String PARAM_NAyS_ALIM_ACA5;
    String PARAM_NAyS_ALIM_ACA6;
    String PARAM_NAyS_ALIM_ACA7;
    String PARAM_NAyS_ALIM_ACA8;
    String PARAM_NAyS_SALID_VAC1;
    String PARAM_NAyS_SALID_VAC2;
    String PARAM_NAyS_SALID_VAC3;
    String PARAM_NAyS_SALID_VAC4;
    String PARAM_NAyS_SALID_VAC5;
    String PARAM_NAyS_SALID_VAC6;
    String PARAM_NAyS_SALID_VAC7;
    String PARAM_NAyS_SALID_VAC8;
    String PARAM_NAyS_SALID_ACA1;
    String PARAM_NAyS_SALID_ACA2;
    String PARAM_NAyS_SALID_ACA3;
    String PARAM_NAyS_SALID_ACA4;
    String PARAM_NAyS_SALID_ACA5;
    String PARAM_NAyS_SALID_ACA6;
    String PARAM_NAyS_SALID_ACA7;
    String PARAM_NAyS_SALID_ACA8;

    public DCPower(String ID_fORMATO, String GRAL_FOLIO_PRETRABAJO, String GRAL_CLIENTE, String GRAL_DIRECCION, String GRAL_CONTACTO, String GRAL_TELEFONO, String GRAL_MAIL, String GRAL_PROYECTO, String GRAL_REFERENCIA, String GRAL_SR, String GRAL_TASK, String GRAL_TIPO_SERVICIO, String GRAL_ESPECIFICACION, String GRAL_FRECUENCIA, String GRAL_NTAG, String GRAL_MODELO, String GRAL_SERIE, String GRAL_SERIE2, String GRAL_FECHA_INICIO, String GRAL_FECHA_FIN, String PARAM_GRALS_TIPO, String PARAM_GRALS_N_ESPECIFICAION, String PARAM_GRALS_CAPACIDAD, String PARAM_GRALS_CONFIGURACION, String PARAM_GRALS_CARGA_ACT, String PARAM_INV_RECTIFICADORES_MODELO, String PARAM_INV_RECTIFICADORES_N_ESPECIFICACION, String PARAM_INV_RECTIFICADORES_CAPACIDAD, String PARAM_INV_RECTIFICADORES_R1, String PARAM_INV_RECTIFICADORES_R2, String PARAM_INV_RECTIFICADORES_R3, String PARAM_INV_RECTIFICADORES_R4, String PARAM_INV_RECTIFICADORES_R5, String PARAM_INV_RECTIFICADORES_R6, String PARAM_INV_RECTIFICADORES_R7, String PARAM_INV_RECTIFICADORES_R8, String PARAM_INV_RECTIFICADORES_R9, String PARAM_INV_RECTIFICADORES_R10, String PARAM_INV_RECTIFICADORES_R11, String PARAM_INV_RECTIFICADORES_R12, String PARAM_INV_RECTIFICADORES_R13, String PARAM_INV_RECTIFICADORES_R14, String PARAM_INV_RECTIFICADORES_R15, String PARAM_INV_RECTIFICADORES_R16, String PARAM_INV_RECTIFICADORES_R17, String PARAM_INV_RECTIFICADORES_R18, String PARAM_INV_RECTIFICADORES_R19, String PARAM_INV_RECTIFICADORES_R20, String PARAM_INV_RECTIFICADORES_R21, String PARAM_INV_RECTIFICADORES_R22, String PARAM_INV_RECTIFICADORES_R23, String PARAM_INV_RECTIFICADORES_R24, String PARAM_INV_RECTIFICADORES_R25, String PARAM_INV_RECTIFICADORES_R26, String PARAM_INV_RECTIFICADORES_R27, String PARAM_INV_RECTIFICADORES_R28, String PARAM_INV_RECTIFICADORES_R29, String PARAM_INV_RECTIFICADORES_R30, String PARAM_INV_RECTIFICADORES_R31, String PARAM_INV_RECTIFICADORES_R32, String PARAM_INV_GABINETES_NA, String PARAM_INV_GABINETES_ESPECIFIC, String PARAM_INV_GABINETES_GAB1, String PARAM_INV_GABINETES_GAB2, String PARAM_INV_GABINETES_GAB3, String PARAM_INV_GABINETES_GAB4, String PARAM_INV_GABINETES_GAB5, String PARAM_INV_GABINETES_GAB6, String PARAM_SUPRESOR_NA, String PARAM_SUPRESOR_MARCA, String PARAM_SUPRESOR_MODELO, String PARAM_SUPRESOR_INSTALAC, String PARAM_SUPRESOR_CALIBRE_CONEXION, String PARAM_SUPRESOR_CAPACIDAD, String PARAM_SUPRESOR_CALIBRE_TIERRAS, String PARAM_AyO_PLANTA_ALIMENT_M1, String PARAM_AyO_PLANTA_ALIMENT_M2, String PARAM_AyO_PLANTA_ALIMENT_M3, String PARAM_AyO_PLANTA_ALIMENT_M4, String PARAM_AyO_PLANTA_ALIMENT_M5, String PARAM_AyO_PLANTA_ALIMENT_M6, String PARAM_AyO_PLANTA_ALIMENT_M7, String PARAM_AyO_PLANTA_ALIMENT_M8, String PARAM_AyO_PLANTA_OPERAC_M1, String PARAM_AyO_PLANTA_OPERAC_M2, String PARAM_AyO_PLANTA_OPERAC_M3, String PARAM_AyO_PLANTA_OPERAC_M4, String PARAM_AyO_PLANTA_OPERAC_M5, String PARAM_AyO_PLANTA_OPERAC_M6, String PARAM_AyO_PLANTA_OPERAC_M7, String PARAM_AyO_PLANTA_OPERAC_M8, String PARAM_AyO_PLANTA_OPERAC_M9, String PARAM_AyO_PLANTA_OPERAC_M10, String PARAM_AyO_PLANTA_LIMPIEZA_INTERNA, String PARAM_AyO_PLANTA_LIMPIEZA_INDV, String PARAM_AyO_PLANTA_VERIFICAION, String PARAM_STPF_DC_NA, String PARAM_STPF_DC_CAMP1, String PARAM_STPF_DC_CAMP2, String PARAM_STPF_DC_CAMP3, String PARAM_STPF_DC_CAMP4, String PARAM_STPF_DC_CAMP5, String PARAM_STPF_DC_CAMP6, String PARAM_STPF_DC_CAMP7, String PARAM_STPF_DC_CAMP8, String PARAM_ITPF_DC_NA, String PARAM_ITPF_DC_CAMP1, String PARAM_ITPF_DC_CAMP2, String PARAM_ITPF_DC_CAMP3, String PARAM_ITPF_DC_CAMP4, String PARAM_ITPF_DC_CAMP5, String PARAM_ITPF_DC_CAMP6, String PARAM_ITPF_DC_CAMP7, String PARAM_SISTEMA_DIST_NA, String PARAM_SISTEMA_DIST_MODELO, String PARAM_SISTEMA_DIST_MARCA, String PARAM_SISTEMA_DIST_ESPECIFI, String PARAM_SISTEMA_DIST_CAPACIDAD, String PARAM_SISTEMA_DIST_CONFIGURACION, String PARAM_IDR_NA, String PARAM_IDR_CAMP1, String PARAM_IDR_CAMP2, String PARAM_IDR_CAMP3, String PARAM_IDR_CAMP4, String PARAM_IDR_CAMP5, String PARAM_IDR_CAMP6, String PARAM_IDR_CAMP7, String PARAM_IDR_BREAK1, String PARAM_IDR_BREAK2, String PARAM_IDR_BREAK3, String PARAM_IDR_BREAK4, String PARAM_IDR_BREAK5, String PARAM_IDR_BREAK6, String PARAM_IDR_BREAK7, String PARAM_IDR_BREAK8, String PARAM_SISTEMA_INVER_NA, String PARAM_SISTEMA_INVER_MODELO, String PARAM_SISTEMA_INVER_MARCA, String PARAM_SISTEMA_INVER_ESPEC, String PARAM_SISTEMA_INVER_CAPACIDAD, String PARAM_SISTEMA_INVER_CONFG, String PARAM_SISTEMA_INVER_A_PIEZA, String PARAM_SISTEMA_INVER_A_INV1, String PARAM_SISTEMA_INVER_A_INV2, String PARAM_SISTEMA_INVER_A_INV3, String PARAM_SISTEMA_INVER_A_INV4, String PARAM_SISTEMA_INVER_A_INV5, String PARAM_SISTEMA_INVER_A_INV6, String PARAM_SISTEMA_INVER_A_INV7, String PARAM_SISTEMA_INVER_A_INV8, String PARAM_SISTEMA_INVER_A_INV9, String PARAM_SISTEMA_INVER_A_INV10, String PARAM_SISTEMA_INVER_B_PIEZA, String PARAM_SISTEMA_INVER_B_INV1, String PARAM_SISTEMA_INVER_B_INV2, String PARAM_SISTEMA_INVER_B_INV3, String PARAM_SISTEMA_INVER_B_INV4, String PARAM_SISTEMA_INVER_B_INV5, String PARAM_SISTEMA_INVER_B_INV6, String PARAM_SISTEMA_INVER_B_INV7, String PARAM_SISTEMA_INVER_B_INV8, String PARAM_SISTEMA_INVER_B_INV9, String PARAM_SISTEMA_INVER_B_INV10, String PARAM_SISTEMA_INVER_C_PIEZA, String PARAM_SISTEMA_INVER_C_INV1, String PARAM_SISTEMA_INVER_C_INV2, String PARAM_SISTEMA_INVER_C_INV3, String PARAM_SISTEMA_INVER_C_INV4, String PARAM_SISTEMA_INVER_C_INV5, String PARAM_SISTEMA_INVER_C_INV6, String PARAM_SISTEMA_INVER_C_INV7, String PARAM_SISTEMA_INVER_C_INV8, String PARAM_SISTEMA_INVER_C_INV9, String PARAM_SISTEMA_INVER_C_INV10, String PARAM_SISTEMA_INVER_VERI1, String PARAM_SISTEMA_INVER_VERI2, String PARAM_SISTEMA_INVER_VERI3, String PARAM_SISTEMA_INVER_VERI4, String PARAM_SISTEMA_INVER_LIMP, String PARAM_NAyS_ALIM_VAC1, String PARAM_NAyS_ALIM_VAC2, String PARAM_NAyS_ALIM_VAC3, String PARAM_NAyS_ALIM_VAC4, String PARAM_NAyS_ALIM_VAC5, String PARAM_NAyS_ALIM_VAC6, String PARAM_NAyS_ALIM_VAC7, String PARAM_NAyS_ALIM_VAC8, String PARAM_NAyS_ALIM_ACA1, String PARAM_NAyS_ALIM_ACA2, String PARAM_NAyS_ALIM_ACA3, String PARAM_NAyS_ALIM_ACA4, String PARAM_NAyS_ALIM_ACA5, String PARAM_NAyS_ALIM_ACA6, String PARAM_NAyS_ALIM_ACA7, String PARAM_NAyS_ALIM_ACA8, String PARAM_NAyS_SALID_VAC1, String PARAM_NAyS_SALID_VAC2, String PARAM_NAyS_SALID_VAC3, String PARAM_NAyS_SALID_VAC4, String PARAM_NAyS_SALID_VAC5, String PARAM_NAyS_SALID_VAC6, String PARAM_NAyS_SALID_VAC7, String PARAM_NAyS_SALID_VAC8, String PARAM_NAyS_SALID_ACA1, String PARAM_NAyS_SALID_ACA2, String PARAM_NAyS_SALID_ACA3, String PARAM_NAyS_SALID_ACA4, String PARAM_NAyS_SALID_ACA5, String PARAM_NAyS_SALID_ACA6, String PARAM_NAyS_SALID_ACA7, String PARAM_NAyS_SALID_ACA8) {
        this.ID_fORMATO = ID_fORMATO;
        this.GRAL_FOLIO_PRETRABAJO = GRAL_FOLIO_PRETRABAJO;
        this.GRAL_CLIENTE = GRAL_CLIENTE;
        this.GRAL_DIRECCION = GRAL_DIRECCION;
        this.GRAL_CONTACTO = GRAL_CONTACTO;
        this.GRAL_TELEFONO = GRAL_TELEFONO;
        this.GRAL_MAIL = GRAL_MAIL;
        this.GRAL_PROYECTO = GRAL_PROYECTO;
        this.GRAL_REFERENCIA = GRAL_REFERENCIA;
        this.GRAL_SR = GRAL_SR;
        this.GRAL_TASK = GRAL_TASK;
        this.GRAL_TIPO_SERVICIO = GRAL_TIPO_SERVICIO;
        this.GRAL_ESPECIFICACION = GRAL_ESPECIFICACION;
        this.GRAL_FRECUENCIA = GRAL_FRECUENCIA;
        this.GRAL_NTAG = GRAL_NTAG;
        this.GRAL_MODELO = GRAL_MODELO;
        this.GRAL_SERIE = GRAL_SERIE;
        this.GRAL_SERIE2 = GRAL_SERIE2;
        this.GRAL_FECHA_INICIO = GRAL_FECHA_INICIO;
        this.GRAL_FECHA_FIN = GRAL_FECHA_FIN;
        this.PARAM_GRALS_TIPO = PARAM_GRALS_TIPO;
        this.PARAM_GRALS_N_ESPECIFICAION = PARAM_GRALS_N_ESPECIFICAION;
        this.PARAM_GRALS_CAPACIDAD = PARAM_GRALS_CAPACIDAD;
        this.PARAM_GRALS_CONFIGURACION = PARAM_GRALS_CONFIGURACION;
        this.PARAM_GRALS_CARGA_ACT = PARAM_GRALS_CARGA_ACT;
        this.PARAM_INV_RECTIFICADORES_MODELO = PARAM_INV_RECTIFICADORES_MODELO;
        this.PARAM_INV_RECTIFICADORES_N_ESPECIFICACION = PARAM_INV_RECTIFICADORES_N_ESPECIFICACION;
        this.PARAM_INV_RECTIFICADORES_CAPACIDAD = PARAM_INV_RECTIFICADORES_CAPACIDAD;
        this.PARAM_INV_RECTIFICADORES_R1 = PARAM_INV_RECTIFICADORES_R1;
        this.PARAM_INV_RECTIFICADORES_R2 = PARAM_INV_RECTIFICADORES_R2;
        this.PARAM_INV_RECTIFICADORES_R3 = PARAM_INV_RECTIFICADORES_R3;
        this.PARAM_INV_RECTIFICADORES_R4 = PARAM_INV_RECTIFICADORES_R4;
        this.PARAM_INV_RECTIFICADORES_R5 = PARAM_INV_RECTIFICADORES_R5;
        this.PARAM_INV_RECTIFICADORES_R6 = PARAM_INV_RECTIFICADORES_R6;
        this.PARAM_INV_RECTIFICADORES_R7 = PARAM_INV_RECTIFICADORES_R7;
        this.PARAM_INV_RECTIFICADORES_R8 = PARAM_INV_RECTIFICADORES_R8;
        this.PARAM_INV_RECTIFICADORES_R9 = PARAM_INV_RECTIFICADORES_R9;
        this.PARAM_INV_RECTIFICADORES_R10 = PARAM_INV_RECTIFICADORES_R10;
        this.PARAM_INV_RECTIFICADORES_R11 = PARAM_INV_RECTIFICADORES_R11;
        this.PARAM_INV_RECTIFICADORES_R12 = PARAM_INV_RECTIFICADORES_R12;
        this.PARAM_INV_RECTIFICADORES_R13 = PARAM_INV_RECTIFICADORES_R13;
        this.PARAM_INV_RECTIFICADORES_R14 = PARAM_INV_RECTIFICADORES_R14;
        this.PARAM_INV_RECTIFICADORES_R15 = PARAM_INV_RECTIFICADORES_R15;
        this.PARAM_INV_RECTIFICADORES_R16 = PARAM_INV_RECTIFICADORES_R16;
        this.PARAM_INV_RECTIFICADORES_R17 = PARAM_INV_RECTIFICADORES_R17;
        this.PARAM_INV_RECTIFICADORES_R18 = PARAM_INV_RECTIFICADORES_R18;
        this.PARAM_INV_RECTIFICADORES_R19 = PARAM_INV_RECTIFICADORES_R19;
        this.PARAM_INV_RECTIFICADORES_R20 = PARAM_INV_RECTIFICADORES_R20;
        this.PARAM_INV_RECTIFICADORES_R21 = PARAM_INV_RECTIFICADORES_R21;
        this.PARAM_INV_RECTIFICADORES_R22 = PARAM_INV_RECTIFICADORES_R22;
        this.PARAM_INV_RECTIFICADORES_R23 = PARAM_INV_RECTIFICADORES_R23;
        this.PARAM_INV_RECTIFICADORES_R24 = PARAM_INV_RECTIFICADORES_R24;
        this.PARAM_INV_RECTIFICADORES_R25 = PARAM_INV_RECTIFICADORES_R25;
        this.PARAM_INV_RECTIFICADORES_R26 = PARAM_INV_RECTIFICADORES_R26;
        this.PARAM_INV_RECTIFICADORES_R27 = PARAM_INV_RECTIFICADORES_R27;
        this.PARAM_INV_RECTIFICADORES_R28 = PARAM_INV_RECTIFICADORES_R28;
        this.PARAM_INV_RECTIFICADORES_R29 = PARAM_INV_RECTIFICADORES_R29;
        this.PARAM_INV_RECTIFICADORES_R30 = PARAM_INV_RECTIFICADORES_R30;
        this.PARAM_INV_RECTIFICADORES_R31 = PARAM_INV_RECTIFICADORES_R31;
        this.PARAM_INV_RECTIFICADORES_R32 = PARAM_INV_RECTIFICADORES_R32;
        this.PARAM_INV_GABINETES_NA = PARAM_INV_GABINETES_NA;
        this.PARAM_INV_GABINETES_ESPECIFIC = PARAM_INV_GABINETES_ESPECIFIC;
        this.PARAM_INV_GABINETES_GAB1 = PARAM_INV_GABINETES_GAB1;
        this.PARAM_INV_GABINETES_GAB2 = PARAM_INV_GABINETES_GAB2;
        this.PARAM_INV_GABINETES_GAB3 = PARAM_INV_GABINETES_GAB3;
        this.PARAM_INV_GABINETES_GAB4 = PARAM_INV_GABINETES_GAB4;
        this.PARAM_INV_GABINETES_GAB5 = PARAM_INV_GABINETES_GAB5;
        this.PARAM_INV_GABINETES_GAB6 = PARAM_INV_GABINETES_GAB6;
        this.PARAM_SUPRESOR_NA = PARAM_SUPRESOR_NA;
        this.PARAM_SUPRESOR_MARCA = PARAM_SUPRESOR_MARCA;
        this.PARAM_SUPRESOR_MODELO = PARAM_SUPRESOR_MODELO;
        this.PARAM_SUPRESOR_INSTALAC = PARAM_SUPRESOR_INSTALAC;
        this.PARAM_SUPRESOR_CALIBRE_CONEXION = PARAM_SUPRESOR_CALIBRE_CONEXION;
        this.PARAM_SUPRESOR_CAPACIDAD = PARAM_SUPRESOR_CAPACIDAD;
        this.PARAM_SUPRESOR_CALIBRE_TIERRAS = PARAM_SUPRESOR_CALIBRE_TIERRAS;
        this.PARAM_AyO_PLANTA_ALIMENT_M1 = PARAM_AyO_PLANTA_ALIMENT_M1;
        this.PARAM_AyO_PLANTA_ALIMENT_M2 = PARAM_AyO_PLANTA_ALIMENT_M2;
        this.PARAM_AyO_PLANTA_ALIMENT_M3 = PARAM_AyO_PLANTA_ALIMENT_M3;
        this.PARAM_AyO_PLANTA_ALIMENT_M4 = PARAM_AyO_PLANTA_ALIMENT_M4;
        this.PARAM_AyO_PLANTA_ALIMENT_M5 = PARAM_AyO_PLANTA_ALIMENT_M5;
        this.PARAM_AyO_PLANTA_ALIMENT_M6 = PARAM_AyO_PLANTA_ALIMENT_M6;
        this.PARAM_AyO_PLANTA_ALIMENT_M7 = PARAM_AyO_PLANTA_ALIMENT_M7;
        this.PARAM_AyO_PLANTA_ALIMENT_M8 = PARAM_AyO_PLANTA_ALIMENT_M8;
        this.PARAM_AyO_PLANTA_OPERAC_M1 = PARAM_AyO_PLANTA_OPERAC_M1;
        this.PARAM_AyO_PLANTA_OPERAC_M2 = PARAM_AyO_PLANTA_OPERAC_M2;
        this.PARAM_AyO_PLANTA_OPERAC_M3 = PARAM_AyO_PLANTA_OPERAC_M3;
        this.PARAM_AyO_PLANTA_OPERAC_M4 = PARAM_AyO_PLANTA_OPERAC_M4;
        this.PARAM_AyO_PLANTA_OPERAC_M5 = PARAM_AyO_PLANTA_OPERAC_M5;
        this.PARAM_AyO_PLANTA_OPERAC_M6 = PARAM_AyO_PLANTA_OPERAC_M6;
        this.PARAM_AyO_PLANTA_OPERAC_M7 = PARAM_AyO_PLANTA_OPERAC_M7;
        this.PARAM_AyO_PLANTA_OPERAC_M8 = PARAM_AyO_PLANTA_OPERAC_M8;
        this.PARAM_AyO_PLANTA_OPERAC_M9 = PARAM_AyO_PLANTA_OPERAC_M9;
        this.PARAM_AyO_PLANTA_OPERAC_M10 = PARAM_AyO_PLANTA_OPERAC_M10;
        this.PARAM_AyO_PLANTA_LIMPIEZA_INTERNA = PARAM_AyO_PLANTA_LIMPIEZA_INTERNA;
        this.PARAM_AyO_PLANTA_LIMPIEZA_INDV = PARAM_AyO_PLANTA_LIMPIEZA_INDV;
        this.PARAM_AyO_PLANTA_VERIFICAION = PARAM_AyO_PLANTA_VERIFICAION;
        this.PARAM_STPF_DC_NA = PARAM_STPF_DC_NA;
        this.PARAM_STPF_DC_CAMP1 = PARAM_STPF_DC_CAMP1;
        this.PARAM_STPF_DC_CAMP2 = PARAM_STPF_DC_CAMP2;
        this.PARAM_STPF_DC_CAMP3 = PARAM_STPF_DC_CAMP3;
        this.PARAM_STPF_DC_CAMP4 = PARAM_STPF_DC_CAMP4;
        this.PARAM_STPF_DC_CAMP5 = PARAM_STPF_DC_CAMP5;
        this.PARAM_STPF_DC_CAMP6 = PARAM_STPF_DC_CAMP6;
        this.PARAM_STPF_DC_CAMP7 = PARAM_STPF_DC_CAMP7;
        this.PARAM_STPF_DC_CAMP8 = PARAM_STPF_DC_CAMP8;
        this.PARAM_ITPF_DC_NA = PARAM_ITPF_DC_NA;
        this.PARAM_ITPF_DC_CAMP1 = PARAM_ITPF_DC_CAMP1;
        this.PARAM_ITPF_DC_CAMP2 = PARAM_ITPF_DC_CAMP2;
        this.PARAM_ITPF_DC_CAMP3 = PARAM_ITPF_DC_CAMP3;
        this.PARAM_ITPF_DC_CAMP4 = PARAM_ITPF_DC_CAMP4;
        this.PARAM_ITPF_DC_CAMP5 = PARAM_ITPF_DC_CAMP5;
        this.PARAM_ITPF_DC_CAMP6 = PARAM_ITPF_DC_CAMP6;
        this.PARAM_ITPF_DC_CAMP7 = PARAM_ITPF_DC_CAMP7;
        this.PARAM_SISTEMA_DIST_NA = PARAM_SISTEMA_DIST_NA;
        this.PARAM_SISTEMA_DIST_MODELO = PARAM_SISTEMA_DIST_MODELO;
        this.PARAM_SISTEMA_DIST_MARCA = PARAM_SISTEMA_DIST_MARCA;
        this.PARAM_SISTEMA_DIST_ESPECIFI = PARAM_SISTEMA_DIST_ESPECIFI;
        this.PARAM_SISTEMA_DIST_CAPACIDAD = PARAM_SISTEMA_DIST_CAPACIDAD;
        this.PARAM_SISTEMA_DIST_CONFIGURACION = PARAM_SISTEMA_DIST_CONFIGURACION;
        this.PARAM_IDR_NA = PARAM_IDR_NA;
        this.PARAM_IDR_CAMP1 = PARAM_IDR_CAMP1;
        this.PARAM_IDR_CAMP2 = PARAM_IDR_CAMP2;
        this.PARAM_IDR_CAMP3 = PARAM_IDR_CAMP3;
        this.PARAM_IDR_CAMP4 = PARAM_IDR_CAMP4;
        this.PARAM_IDR_CAMP5 = PARAM_IDR_CAMP5;
        this.PARAM_IDR_CAMP6 = PARAM_IDR_CAMP6;
        this.PARAM_IDR_CAMP7 = PARAM_IDR_CAMP7;
        this.PARAM_IDR_BREAK1 = PARAM_IDR_BREAK1;
        this.PARAM_IDR_BREAK2 = PARAM_IDR_BREAK2;
        this.PARAM_IDR_BREAK3 = PARAM_IDR_BREAK3;
        this.PARAM_IDR_BREAK4 = PARAM_IDR_BREAK4;
        this.PARAM_IDR_BREAK5 = PARAM_IDR_BREAK5;
        this.PARAM_IDR_BREAK6 = PARAM_IDR_BREAK6;
        this.PARAM_IDR_BREAK7 = PARAM_IDR_BREAK7;
        this.PARAM_IDR_BREAK8 = PARAM_IDR_BREAK8;
        this.PARAM_SISTEMA_INVER_NA = PARAM_SISTEMA_INVER_NA;
        this.PARAM_SISTEMA_INVER_MODELO = PARAM_SISTEMA_INVER_MODELO;
        this.PARAM_SISTEMA_INVER_MARCA = PARAM_SISTEMA_INVER_MARCA;
        this.PARAM_SISTEMA_INVER_ESPEC = PARAM_SISTEMA_INVER_ESPEC;
        this.PARAM_SISTEMA_INVER_CAPACIDAD = PARAM_SISTEMA_INVER_CAPACIDAD;
        this.PARAM_SISTEMA_INVER_CONFG = PARAM_SISTEMA_INVER_CONFG;
        this.PARAM_SISTEMA_INVER_A_PIEZA = PARAM_SISTEMA_INVER_A_PIEZA;
        this.PARAM_SISTEMA_INVER_A_INV1 = PARAM_SISTEMA_INVER_A_INV1;
        this.PARAM_SISTEMA_INVER_A_INV2 = PARAM_SISTEMA_INVER_A_INV2;
        this.PARAM_SISTEMA_INVER_A_INV3 = PARAM_SISTEMA_INVER_A_INV3;
        this.PARAM_SISTEMA_INVER_A_INV4 = PARAM_SISTEMA_INVER_A_INV4;
        this.PARAM_SISTEMA_INVER_A_INV5 = PARAM_SISTEMA_INVER_A_INV5;
        this.PARAM_SISTEMA_INVER_A_INV6 = PARAM_SISTEMA_INVER_A_INV6;
        this.PARAM_SISTEMA_INVER_A_INV7 = PARAM_SISTEMA_INVER_A_INV7;
        this.PARAM_SISTEMA_INVER_A_INV8 = PARAM_SISTEMA_INVER_A_INV8;
        this.PARAM_SISTEMA_INVER_A_INV9 = PARAM_SISTEMA_INVER_A_INV9;
        this.PARAM_SISTEMA_INVER_A_INV10 = PARAM_SISTEMA_INVER_A_INV10;
        this.PARAM_SISTEMA_INVER_B_PIEZA = PARAM_SISTEMA_INVER_B_PIEZA;
        this.PARAM_SISTEMA_INVER_B_INV1 = PARAM_SISTEMA_INVER_B_INV1;
        this.PARAM_SISTEMA_INVER_B_INV2 = PARAM_SISTEMA_INVER_B_INV2;
        this.PARAM_SISTEMA_INVER_B_INV3 = PARAM_SISTEMA_INVER_B_INV3;
        this.PARAM_SISTEMA_INVER_B_INV4 = PARAM_SISTEMA_INVER_B_INV4;
        this.PARAM_SISTEMA_INVER_B_INV5 = PARAM_SISTEMA_INVER_B_INV5;
        this.PARAM_SISTEMA_INVER_B_INV6 = PARAM_SISTEMA_INVER_B_INV6;
        this.PARAM_SISTEMA_INVER_B_INV7 = PARAM_SISTEMA_INVER_B_INV7;
        this.PARAM_SISTEMA_INVER_B_INV8 = PARAM_SISTEMA_INVER_B_INV8;
        this.PARAM_SISTEMA_INVER_B_INV9 = PARAM_SISTEMA_INVER_B_INV9;
        this.PARAM_SISTEMA_INVER_B_INV10 = PARAM_SISTEMA_INVER_B_INV10;
        this.PARAM_SISTEMA_INVER_C_PIEZA = PARAM_SISTEMA_INVER_C_PIEZA;
        this.PARAM_SISTEMA_INVER_C_INV1 = PARAM_SISTEMA_INVER_C_INV1;
        this.PARAM_SISTEMA_INVER_C_INV2 = PARAM_SISTEMA_INVER_C_INV2;
        this.PARAM_SISTEMA_INVER_C_INV3 = PARAM_SISTEMA_INVER_C_INV3;
        this.PARAM_SISTEMA_INVER_C_INV4 = PARAM_SISTEMA_INVER_C_INV4;
        this.PARAM_SISTEMA_INVER_C_INV5 = PARAM_SISTEMA_INVER_C_INV5;
        this.PARAM_SISTEMA_INVER_C_INV6 = PARAM_SISTEMA_INVER_C_INV6;
        this.PARAM_SISTEMA_INVER_C_INV7 = PARAM_SISTEMA_INVER_C_INV7;
        this.PARAM_SISTEMA_INVER_C_INV8 = PARAM_SISTEMA_INVER_C_INV8;
        this.PARAM_SISTEMA_INVER_C_INV9 = PARAM_SISTEMA_INVER_C_INV9;
        this.PARAM_SISTEMA_INVER_C_INV10 = PARAM_SISTEMA_INVER_C_INV10;
        this.PARAM_SISTEMA_INVER_VERI1 = PARAM_SISTEMA_INVER_VERI1;
        this.PARAM_SISTEMA_INVER_VERI2 = PARAM_SISTEMA_INVER_VERI2;
        this.PARAM_SISTEMA_INVER_VERI3 = PARAM_SISTEMA_INVER_VERI3;
        this.PARAM_SISTEMA_INVER_VERI4 = PARAM_SISTEMA_INVER_VERI4;
        this.PARAM_SISTEMA_INVER_LIMP = PARAM_SISTEMA_INVER_LIMP;
        this.PARAM_NAyS_ALIM_VAC1 = PARAM_NAyS_ALIM_VAC1;
        this.PARAM_NAyS_ALIM_VAC2 = PARAM_NAyS_ALIM_VAC2;
        this.PARAM_NAyS_ALIM_VAC3 = PARAM_NAyS_ALIM_VAC3;
        this.PARAM_NAyS_ALIM_VAC4 = PARAM_NAyS_ALIM_VAC4;
        this.PARAM_NAyS_ALIM_VAC5 = PARAM_NAyS_ALIM_VAC5;
        this.PARAM_NAyS_ALIM_VAC6 = PARAM_NAyS_ALIM_VAC6;
        this.PARAM_NAyS_ALIM_VAC7 = PARAM_NAyS_ALIM_VAC7;
        this.PARAM_NAyS_ALIM_VAC8 = PARAM_NAyS_ALIM_VAC8;
        this.PARAM_NAyS_ALIM_ACA1 = PARAM_NAyS_ALIM_ACA1;
        this.PARAM_NAyS_ALIM_ACA2 = PARAM_NAyS_ALIM_ACA2;
        this.PARAM_NAyS_ALIM_ACA3 = PARAM_NAyS_ALIM_ACA3;
        this.PARAM_NAyS_ALIM_ACA4 = PARAM_NAyS_ALIM_ACA4;
        this.PARAM_NAyS_ALIM_ACA5 = PARAM_NAyS_ALIM_ACA5;
        this.PARAM_NAyS_ALIM_ACA6 = PARAM_NAyS_ALIM_ACA6;
        this.PARAM_NAyS_ALIM_ACA7 = PARAM_NAyS_ALIM_ACA7;
        this.PARAM_NAyS_ALIM_ACA8 = PARAM_NAyS_ALIM_ACA8;
        this.PARAM_NAyS_SALID_VAC1 = PARAM_NAyS_SALID_VAC1;
        this.PARAM_NAyS_SALID_VAC2 = PARAM_NAyS_SALID_VAC2;
        this.PARAM_NAyS_SALID_VAC3 = PARAM_NAyS_SALID_VAC3;
        this.PARAM_NAyS_SALID_VAC4 = PARAM_NAyS_SALID_VAC4;
        this.PARAM_NAyS_SALID_VAC5 = PARAM_NAyS_SALID_VAC5;
        this.PARAM_NAyS_SALID_VAC6 = PARAM_NAyS_SALID_VAC6;
        this.PARAM_NAyS_SALID_VAC7 = PARAM_NAyS_SALID_VAC7;
        this.PARAM_NAyS_SALID_VAC8 = PARAM_NAyS_SALID_VAC8;
        this.PARAM_NAyS_SALID_ACA1 = PARAM_NAyS_SALID_ACA1;
        this.PARAM_NAyS_SALID_ACA2 = PARAM_NAyS_SALID_ACA2;
        this.PARAM_NAyS_SALID_ACA3 = PARAM_NAyS_SALID_ACA3;
        this.PARAM_NAyS_SALID_ACA4 = PARAM_NAyS_SALID_ACA4;
        this.PARAM_NAyS_SALID_ACA5 = PARAM_NAyS_SALID_ACA5;
        this.PARAM_NAyS_SALID_ACA6 = PARAM_NAyS_SALID_ACA6;
        this.PARAM_NAyS_SALID_ACA7 = PARAM_NAyS_SALID_ACA7;
        this.PARAM_NAyS_SALID_ACA8 = PARAM_NAyS_SALID_ACA8;
    }


    public String getID_fORMATO() {
        return ID_fORMATO;
    }

    public void setID_fORMATO(String ID_fORMATO) {
        this.ID_fORMATO = ID_fORMATO;
    }

    public String getGRAL_FOLIO_PRETRABAJO() {
        return GRAL_FOLIO_PRETRABAJO;
    }

    public void setGRAL_FOLIO_PRETRABAJO(String GRAL_FOLIO_PRETRABAJO) {
        this.GRAL_FOLIO_PRETRABAJO = GRAL_FOLIO_PRETRABAJO;
    }

    public String getGRAL_CLIENTE() {
        return GRAL_CLIENTE;
    }

    public void setGRAL_CLIENTE(String GRAL_CLIENTE) {
        this.GRAL_CLIENTE = GRAL_CLIENTE;
    }

    public String getGRAL_DIRECCION() {
        return GRAL_DIRECCION;
    }

    public void setGRAL_DIRECCION(String GRAL_DIRECCION) {
        this.GRAL_DIRECCION = GRAL_DIRECCION;
    }

    public String getGRAL_CONTACTO() {
        return GRAL_CONTACTO;
    }

    public void setGRAL_CONTACTO(String GRAL_CONTACTO) {
        this.GRAL_CONTACTO = GRAL_CONTACTO;
    }

    public String getGRAL_TELEFONO() {
        return GRAL_TELEFONO;
    }

    public void setGRAL_TELEFONO(String GRAL_TELEFONO) {
        this.GRAL_TELEFONO = GRAL_TELEFONO;
    }

    public String getGRAL_MAIL() {
        return GRAL_MAIL;
    }

    public void setGRAL_MAIL(String GRAL_MAIL) {
        this.GRAL_MAIL = GRAL_MAIL;
    }

    public String getGRAL_PROYECTO() {
        return GRAL_PROYECTO;
    }

    public void setGRAL_PROYECTO(String GRAL_PROYECTO) {
        this.GRAL_PROYECTO = GRAL_PROYECTO;
    }

    public String getGRAL_REFERENCIA() {
        return GRAL_REFERENCIA;
    }

    public void setGRAL_REFERENCIA(String GRAL_REFERENCIA) {
        this.GRAL_REFERENCIA = GRAL_REFERENCIA;
    }

    public String getGRAL_SR() {
        return GRAL_SR;
    }

    public void setGRAL_SR(String GRAL_SR) {
        this.GRAL_SR = GRAL_SR;
    }

    public String getGRAL_TASK() {
        return GRAL_TASK;
    }

    public void setGRAL_TASK(String GRAL_TASK) {
        this.GRAL_TASK = GRAL_TASK;
    }

    public String getGRAL_TIPO_SERVICIO() {
        return GRAL_TIPO_SERVICIO;
    }

    public void setGRAL_TIPO_SERVICIO(String GRAL_TIPO_SERVICIO) {
        this.GRAL_TIPO_SERVICIO = GRAL_TIPO_SERVICIO;
    }

    public String getGRAL_ESPECIFICACION() {
        return GRAL_ESPECIFICACION;
    }

    public void setGRAL_ESPECIFICACION(String GRAL_ESPECIFICACION) {
        this.GRAL_ESPECIFICACION = GRAL_ESPECIFICACION;
    }

    public String getGRAL_FRECUENCIA() {
        return GRAL_FRECUENCIA;
    }

    public void setGRAL_FRECUENCIA(String GRAL_FRECUENCIA) {
        this.GRAL_FRECUENCIA = GRAL_FRECUENCIA;
    }

    public String getGRAL_NTAG() {
        return GRAL_NTAG;
    }

    public void setGRAL_NTAG(String GRAL_NTAG) {
        this.GRAL_NTAG = GRAL_NTAG;
    }

    public String getGRAL_MODELO() {
        return GRAL_MODELO;
    }

    public void setGRAL_MODELO(String GRAL_MODELO) {
        this.GRAL_MODELO = GRAL_MODELO;
    }

    public String getGRAL_SERIE() {
        return GRAL_SERIE;
    }

    public void setGRAL_SERIE(String GRAL_SERIE) {
        this.GRAL_SERIE = GRAL_SERIE;
    }

    public String getGRAL_SERIE2() {
        return GRAL_SERIE2;
    }

    public void setGRAL_SERIE2(String GRAL_SERIE2) {
        this.GRAL_SERIE2 = GRAL_SERIE2;
    }

    public String getGRAL_FECHA_INICIO() {
        return GRAL_FECHA_INICIO;
    }

    public void setGRAL_FECHA_INICIO(String GRAL_FECHA_INICIO) {
        this.GRAL_FECHA_INICIO = GRAL_FECHA_INICIO;
    }

    public String getGRAL_FECHA_FIN() {
        return GRAL_FECHA_FIN;
    }

    public void setGRAL_FECHA_FIN(String GRAL_FECHA_FIN) {
        this.GRAL_FECHA_FIN = GRAL_FECHA_FIN;
    }

    public String getPARAM_GRALS_TIPO() {
        return PARAM_GRALS_TIPO;
    }

    public void setPARAM_GRALS_TIPO(String PARAM_GRALS_TIPO) {
        this.PARAM_GRALS_TIPO = PARAM_GRALS_TIPO;
    }

    public String getPARAM_GRALS_N_ESPECIFICAION() {
        return PARAM_GRALS_N_ESPECIFICAION;
    }

    public void setPARAM_GRALS_N_ESPECIFICAION(String PARAM_GRALS_N_ESPECIFICAION) {
        this.PARAM_GRALS_N_ESPECIFICAION = PARAM_GRALS_N_ESPECIFICAION;
    }

    public String getPARAM_GRALS_CAPACIDAD() {
        return PARAM_GRALS_CAPACIDAD;
    }

    public void setPARAM_GRALS_CAPACIDAD(String PARAM_GRALS_CAPACIDAD) {
        this.PARAM_GRALS_CAPACIDAD = PARAM_GRALS_CAPACIDAD;
    }

    public String getPARAM_GRALS_CONFIGURACION() {
        return PARAM_GRALS_CONFIGURACION;
    }

    public void setPARAM_GRALS_CONFIGURACION(String PARAM_GRALS_CONFIGURACION) {
        this.PARAM_GRALS_CONFIGURACION = PARAM_GRALS_CONFIGURACION;
    }

    public String getPARAM_GRALS_CARGA_ACT() {
        return PARAM_GRALS_CARGA_ACT;
    }

    public void setPARAM_GRALS_CARGA_ACT(String PARAM_GRALS_CARGA_ACT) {
        this.PARAM_GRALS_CARGA_ACT = PARAM_GRALS_CARGA_ACT;
    }

    public String getPARAM_INV_RECTIFICADORES_MODELO() {
        return PARAM_INV_RECTIFICADORES_MODELO;
    }

    public void setPARAM_INV_RECTIFICADORES_MODELO(String PARAM_INV_RECTIFICADORES_MODELO) {
        this.PARAM_INV_RECTIFICADORES_MODELO = PARAM_INV_RECTIFICADORES_MODELO;
    }

    public String getPARAM_INV_RECTIFICADORES_N_ESPECIFICACION() {
        return PARAM_INV_RECTIFICADORES_N_ESPECIFICACION;
    }

    public void setPARAM_INV_RECTIFICADORES_N_ESPECIFICACION(String PARAM_INV_RECTIFICADORES_N_ESPECIFICACION) {
        this.PARAM_INV_RECTIFICADORES_N_ESPECIFICACION = PARAM_INV_RECTIFICADORES_N_ESPECIFICACION;
    }

    public String getPARAM_INV_RECTIFICADORES_CAPACIDAD() {
        return PARAM_INV_RECTIFICADORES_CAPACIDAD;
    }

    public void setPARAM_INV_RECTIFICADORES_CAPACIDAD(String PARAM_INV_RECTIFICADORES_CAPACIDAD) {
        this.PARAM_INV_RECTIFICADORES_CAPACIDAD = PARAM_INV_RECTIFICADORES_CAPACIDAD;
    }

    public String getPARAM_INV_RECTIFICADORES_R1() {
        return PARAM_INV_RECTIFICADORES_R1;
    }

    public void setPARAM_INV_RECTIFICADORES_R1(String PARAM_INV_RECTIFICADORES_R1) {
        this.PARAM_INV_RECTIFICADORES_R1 = PARAM_INV_RECTIFICADORES_R1;
    }

    public String getPARAM_INV_RECTIFICADORES_R2() {
        return PARAM_INV_RECTIFICADORES_R2;
    }

    public void setPARAM_INV_RECTIFICADORES_R2(String PARAM_INV_RECTIFICADORES_R2) {
        this.PARAM_INV_RECTIFICADORES_R2 = PARAM_INV_RECTIFICADORES_R2;
    }

    public String getPARAM_INV_RECTIFICADORES_R3() {
        return PARAM_INV_RECTIFICADORES_R3;
    }

    public void setPARAM_INV_RECTIFICADORES_R3(String PARAM_INV_RECTIFICADORES_R3) {
        this.PARAM_INV_RECTIFICADORES_R3 = PARAM_INV_RECTIFICADORES_R3;
    }

    public String getPARAM_INV_RECTIFICADORES_R4() {
        return PARAM_INV_RECTIFICADORES_R4;
    }

    public void setPARAM_INV_RECTIFICADORES_R4(String PARAM_INV_RECTIFICADORES_R4) {
        this.PARAM_INV_RECTIFICADORES_R4 = PARAM_INV_RECTIFICADORES_R4;
    }

    public String getPARAM_INV_RECTIFICADORES_R5() {
        return PARAM_INV_RECTIFICADORES_R5;
    }

    public void setPARAM_INV_RECTIFICADORES_R5(String PARAM_INV_RECTIFICADORES_R5) {
        this.PARAM_INV_RECTIFICADORES_R5 = PARAM_INV_RECTIFICADORES_R5;
    }

    public String getPARAM_INV_RECTIFICADORES_R6() {
        return PARAM_INV_RECTIFICADORES_R6;
    }

    public void setPARAM_INV_RECTIFICADORES_R6(String PARAM_INV_RECTIFICADORES_R6) {
        this.PARAM_INV_RECTIFICADORES_R6 = PARAM_INV_RECTIFICADORES_R6;
    }

    public String getPARAM_INV_RECTIFICADORES_R7() {
        return PARAM_INV_RECTIFICADORES_R7;
    }

    public void setPARAM_INV_RECTIFICADORES_R7(String PARAM_INV_RECTIFICADORES_R7) {
        this.PARAM_INV_RECTIFICADORES_R7 = PARAM_INV_RECTIFICADORES_R7;
    }

    public String getPARAM_INV_RECTIFICADORES_R8() {
        return PARAM_INV_RECTIFICADORES_R8;
    }

    public void setPARAM_INV_RECTIFICADORES_R8(String PARAM_INV_RECTIFICADORES_R8) {
        this.PARAM_INV_RECTIFICADORES_R8 = PARAM_INV_RECTIFICADORES_R8;
    }

    public String getPARAM_INV_RECTIFICADORES_R9() {
        return PARAM_INV_RECTIFICADORES_R9;
    }

    public void setPARAM_INV_RECTIFICADORES_R9(String PARAM_INV_RECTIFICADORES_R9) {
        this.PARAM_INV_RECTIFICADORES_R9 = PARAM_INV_RECTIFICADORES_R9;
    }

    public String getPARAM_INV_RECTIFICADORES_R10() {
        return PARAM_INV_RECTIFICADORES_R10;
    }

    public void setPARAM_INV_RECTIFICADORES_R10(String PARAM_INV_RECTIFICADORES_R10) {
        this.PARAM_INV_RECTIFICADORES_R10 = PARAM_INV_RECTIFICADORES_R10;
    }

    public String getPARAM_INV_RECTIFICADORES_R11() {
        return PARAM_INV_RECTIFICADORES_R11;
    }

    public void setPARAM_INV_RECTIFICADORES_R11(String PARAM_INV_RECTIFICADORES_R11) {
        this.PARAM_INV_RECTIFICADORES_R11 = PARAM_INV_RECTIFICADORES_R11;
    }

    public String getPARAM_INV_RECTIFICADORES_R12() {
        return PARAM_INV_RECTIFICADORES_R12;
    }

    public void setPARAM_INV_RECTIFICADORES_R12(String PARAM_INV_RECTIFICADORES_R12) {
        this.PARAM_INV_RECTIFICADORES_R12 = PARAM_INV_RECTIFICADORES_R12;
    }

    public String getPARAM_INV_RECTIFICADORES_R13() {
        return PARAM_INV_RECTIFICADORES_R13;
    }

    public void setPARAM_INV_RECTIFICADORES_R13(String PARAM_INV_RECTIFICADORES_R13) {
        this.PARAM_INV_RECTIFICADORES_R13 = PARAM_INV_RECTIFICADORES_R13;
    }

    public String getPARAM_INV_RECTIFICADORES_R14() {
        return PARAM_INV_RECTIFICADORES_R14;
    }

    public void setPARAM_INV_RECTIFICADORES_R14(String PARAM_INV_RECTIFICADORES_R14) {
        this.PARAM_INV_RECTIFICADORES_R14 = PARAM_INV_RECTIFICADORES_R14;
    }

    public String getPARAM_INV_RECTIFICADORES_R15() {
        return PARAM_INV_RECTIFICADORES_R15;
    }

    public void setPARAM_INV_RECTIFICADORES_R15(String PARAM_INV_RECTIFICADORES_R15) {
        this.PARAM_INV_RECTIFICADORES_R15 = PARAM_INV_RECTIFICADORES_R15;
    }

    public String getPARAM_INV_RECTIFICADORES_R16() {
        return PARAM_INV_RECTIFICADORES_R16;
    }

    public void setPARAM_INV_RECTIFICADORES_R16(String PARAM_INV_RECTIFICADORES_R16) {
        this.PARAM_INV_RECTIFICADORES_R16 = PARAM_INV_RECTIFICADORES_R16;
    }

    public String getPARAM_INV_RECTIFICADORES_R17() {
        return PARAM_INV_RECTIFICADORES_R17;
    }

    public void setPARAM_INV_RECTIFICADORES_R17(String PARAM_INV_RECTIFICADORES_R17) {
        this.PARAM_INV_RECTIFICADORES_R17 = PARAM_INV_RECTIFICADORES_R17;
    }

    public String getPARAM_INV_RECTIFICADORES_R18() {
        return PARAM_INV_RECTIFICADORES_R18;
    }

    public void setPARAM_INV_RECTIFICADORES_R18(String PARAM_INV_RECTIFICADORES_R18) {
        this.PARAM_INV_RECTIFICADORES_R18 = PARAM_INV_RECTIFICADORES_R18;
    }

    public String getPARAM_INV_RECTIFICADORES_R19() {
        return PARAM_INV_RECTIFICADORES_R19;
    }

    public void setPARAM_INV_RECTIFICADORES_R19(String PARAM_INV_RECTIFICADORES_R19) {
        this.PARAM_INV_RECTIFICADORES_R19 = PARAM_INV_RECTIFICADORES_R19;
    }

    public String getPARAM_INV_RECTIFICADORES_R20() {
        return PARAM_INV_RECTIFICADORES_R20;
    }

    public void setPARAM_INV_RECTIFICADORES_R20(String PARAM_INV_RECTIFICADORES_R20) {
        this.PARAM_INV_RECTIFICADORES_R20 = PARAM_INV_RECTIFICADORES_R20;
    }

    public String getPARAM_INV_RECTIFICADORES_R21() {
        return PARAM_INV_RECTIFICADORES_R21;
    }

    public void setPARAM_INV_RECTIFICADORES_R21(String PARAM_INV_RECTIFICADORES_R21) {
        this.PARAM_INV_RECTIFICADORES_R21 = PARAM_INV_RECTIFICADORES_R21;
    }

    public String getPARAM_INV_RECTIFICADORES_R22() {
        return PARAM_INV_RECTIFICADORES_R22;
    }

    public void setPARAM_INV_RECTIFICADORES_R22(String PARAM_INV_RECTIFICADORES_R22) {
        this.PARAM_INV_RECTIFICADORES_R22 = PARAM_INV_RECTIFICADORES_R22;
    }

    public String getPARAM_INV_RECTIFICADORES_R23() {
        return PARAM_INV_RECTIFICADORES_R23;
    }

    public void setPARAM_INV_RECTIFICADORES_R23(String PARAM_INV_RECTIFICADORES_R23) {
        this.PARAM_INV_RECTIFICADORES_R23 = PARAM_INV_RECTIFICADORES_R23;
    }

    public String getPARAM_INV_RECTIFICADORES_R24() {
        return PARAM_INV_RECTIFICADORES_R24;
    }

    public void setPARAM_INV_RECTIFICADORES_R24(String PARAM_INV_RECTIFICADORES_R24) {
        this.PARAM_INV_RECTIFICADORES_R24 = PARAM_INV_RECTIFICADORES_R24;
    }

    public String getPARAM_INV_RECTIFICADORES_R25() {
        return PARAM_INV_RECTIFICADORES_R25;
    }

    public void setPARAM_INV_RECTIFICADORES_R25(String PARAM_INV_RECTIFICADORES_R25) {
        this.PARAM_INV_RECTIFICADORES_R25 = PARAM_INV_RECTIFICADORES_R25;
    }

    public String getPARAM_INV_RECTIFICADORES_R26() {
        return PARAM_INV_RECTIFICADORES_R26;
    }

    public void setPARAM_INV_RECTIFICADORES_R26(String PARAM_INV_RECTIFICADORES_R26) {
        this.PARAM_INV_RECTIFICADORES_R26 = PARAM_INV_RECTIFICADORES_R26;
    }

    public String getPARAM_INV_RECTIFICADORES_R27() {
        return PARAM_INV_RECTIFICADORES_R27;
    }

    public void setPARAM_INV_RECTIFICADORES_R27(String PARAM_INV_RECTIFICADORES_R27) {
        this.PARAM_INV_RECTIFICADORES_R27 = PARAM_INV_RECTIFICADORES_R27;
    }

    public String getPARAM_INV_RECTIFICADORES_R28() {
        return PARAM_INV_RECTIFICADORES_R28;
    }

    public void setPARAM_INV_RECTIFICADORES_R28(String PARAM_INV_RECTIFICADORES_R28) {
        this.PARAM_INV_RECTIFICADORES_R28 = PARAM_INV_RECTIFICADORES_R28;
    }

    public String getPARAM_INV_RECTIFICADORES_R29() {
        return PARAM_INV_RECTIFICADORES_R29;
    }

    public void setPARAM_INV_RECTIFICADORES_R29(String PARAM_INV_RECTIFICADORES_R29) {
        this.PARAM_INV_RECTIFICADORES_R29 = PARAM_INV_RECTIFICADORES_R29;
    }

    public String getPARAM_INV_RECTIFICADORES_R30() {
        return PARAM_INV_RECTIFICADORES_R30;
    }

    public void setPARAM_INV_RECTIFICADORES_R30(String PARAM_INV_RECTIFICADORES_R30) {
        this.PARAM_INV_RECTIFICADORES_R30 = PARAM_INV_RECTIFICADORES_R30;
    }

    public String getPARAM_INV_RECTIFICADORES_R31() {
        return PARAM_INV_RECTIFICADORES_R31;
    }

    public void setPARAM_INV_RECTIFICADORES_R31(String PARAM_INV_RECTIFICADORES_R31) {
        this.PARAM_INV_RECTIFICADORES_R31 = PARAM_INV_RECTIFICADORES_R31;
    }

    public String getPARAM_INV_RECTIFICADORES_R32() {
        return PARAM_INV_RECTIFICADORES_R32;
    }

    public void setPARAM_INV_RECTIFICADORES_R32(String PARAM_INV_RECTIFICADORES_R32) {
        this.PARAM_INV_RECTIFICADORES_R32 = PARAM_INV_RECTIFICADORES_R32;
    }

    public String getPARAM_INV_GABINETES_NA() {
        return PARAM_INV_GABINETES_NA;
    }

    public void setPARAM_INV_GABINETES_NA(String PARAM_INV_GABINETES_NA) {
        this.PARAM_INV_GABINETES_NA = PARAM_INV_GABINETES_NA;
    }

    public String getPARAM_INV_GABINETES_ESPECIFIC() {
        return PARAM_INV_GABINETES_ESPECIFIC;
    }

    public void setPARAM_INV_GABINETES_ESPECIFIC(String PARAM_INV_GABINETES_ESPECIFIC) {
        this.PARAM_INV_GABINETES_ESPECIFIC = PARAM_INV_GABINETES_ESPECIFIC;
    }

    public String getPARAM_INV_GABINETES_GAB1() {
        return PARAM_INV_GABINETES_GAB1;
    }

    public void setPARAM_INV_GABINETES_GAB1(String PARAM_INV_GABINETES_GAB1) {
        this.PARAM_INV_GABINETES_GAB1 = PARAM_INV_GABINETES_GAB1;
    }

    public String getPARAM_INV_GABINETES_GAB2() {
        return PARAM_INV_GABINETES_GAB2;
    }

    public void setPARAM_INV_GABINETES_GAB2(String PARAM_INV_GABINETES_GAB2) {
        this.PARAM_INV_GABINETES_GAB2 = PARAM_INV_GABINETES_GAB2;
    }

    public String getPARAM_INV_GABINETES_GAB3() {
        return PARAM_INV_GABINETES_GAB3;
    }

    public void setPARAM_INV_GABINETES_GAB3(String PARAM_INV_GABINETES_GAB3) {
        this.PARAM_INV_GABINETES_GAB3 = PARAM_INV_GABINETES_GAB3;
    }

    public String getPARAM_INV_GABINETES_GAB4() {
        return PARAM_INV_GABINETES_GAB4;
    }

    public void setPARAM_INV_GABINETES_GAB4(String PARAM_INV_GABINETES_GAB4) {
        this.PARAM_INV_GABINETES_GAB4 = PARAM_INV_GABINETES_GAB4;
    }

    public String getPARAM_INV_GABINETES_GAB5() {
        return PARAM_INV_GABINETES_GAB5;
    }

    public void setPARAM_INV_GABINETES_GAB5(String PARAM_INV_GABINETES_GAB5) {
        this.PARAM_INV_GABINETES_GAB5 = PARAM_INV_GABINETES_GAB5;
    }

    public String getPARAM_INV_GABINETES_GAB6() {
        return PARAM_INV_GABINETES_GAB6;
    }

    public void setPARAM_INV_GABINETES_GAB6(String PARAM_INV_GABINETES_GAB6) {
        this.PARAM_INV_GABINETES_GAB6 = PARAM_INV_GABINETES_GAB6;
    }

    public String getPARAM_SUPRESOR_NA() {
        return PARAM_SUPRESOR_NA;
    }

    public void setPARAM_SUPRESOR_NA(String PARAM_SUPRESOR_NA) {
        this.PARAM_SUPRESOR_NA = PARAM_SUPRESOR_NA;
    }

    public String getPARAM_SUPRESOR_MARCA() {
        return PARAM_SUPRESOR_MARCA;
    }

    public void setPARAM_SUPRESOR_MARCA(String PARAM_SUPRESOR_MARCA) {
        this.PARAM_SUPRESOR_MARCA = PARAM_SUPRESOR_MARCA;
    }

    public String getPARAM_SUPRESOR_MODELO() {
        return PARAM_SUPRESOR_MODELO;
    }

    public void setPARAM_SUPRESOR_MODELO(String PARAM_SUPRESOR_MODELO) {
        this.PARAM_SUPRESOR_MODELO = PARAM_SUPRESOR_MODELO;
    }

    public String getPARAM_SUPRESOR_INSTALAC() {
        return PARAM_SUPRESOR_INSTALAC;
    }

    public void setPARAM_SUPRESOR_INSTALAC(String PARAM_SUPRESOR_INSTALAC) {
        this.PARAM_SUPRESOR_INSTALAC = PARAM_SUPRESOR_INSTALAC;
    }

    public String getPARAM_SUPRESOR_CALIBRE_CONEXION() {
        return PARAM_SUPRESOR_CALIBRE_CONEXION;
    }

    public void setPARAM_SUPRESOR_CALIBRE_CONEXION(String PARAM_SUPRESOR_CALIBRE_CONEXION) {
        this.PARAM_SUPRESOR_CALIBRE_CONEXION = PARAM_SUPRESOR_CALIBRE_CONEXION;
    }

    public String getPARAM_SUPRESOR_CAPACIDAD() {
        return PARAM_SUPRESOR_CAPACIDAD;
    }

    public void setPARAM_SUPRESOR_CAPACIDAD(String PARAM_SUPRESOR_CAPACIDAD) {
        this.PARAM_SUPRESOR_CAPACIDAD = PARAM_SUPRESOR_CAPACIDAD;
    }

    public String getPARAM_SUPRESOR_CALIBRE_TIERRAS() {
        return PARAM_SUPRESOR_CALIBRE_TIERRAS;
    }

    public void setPARAM_SUPRESOR_CALIBRE_TIERRAS(String PARAM_SUPRESOR_CALIBRE_TIERRAS) {
        this.PARAM_SUPRESOR_CALIBRE_TIERRAS = PARAM_SUPRESOR_CALIBRE_TIERRAS;
    }

    public String getPARAM_AyO_PLANTA_ALIMENT_M1() {
        return PARAM_AyO_PLANTA_ALIMENT_M1;
    }

    public void setPARAM_AyO_PLANTA_ALIMENT_M1(String PARAM_AyO_PLANTA_ALIMENT_M1) {
        this.PARAM_AyO_PLANTA_ALIMENT_M1 = PARAM_AyO_PLANTA_ALIMENT_M1;
    }

    public String getPARAM_AyO_PLANTA_ALIMENT_M2() {
        return PARAM_AyO_PLANTA_ALIMENT_M2;
    }

    public void setPARAM_AyO_PLANTA_ALIMENT_M2(String PARAM_AyO_PLANTA_ALIMENT_M2) {
        this.PARAM_AyO_PLANTA_ALIMENT_M2 = PARAM_AyO_PLANTA_ALIMENT_M2;
    }

    public String getPARAM_AyO_PLANTA_ALIMENT_M3() {
        return PARAM_AyO_PLANTA_ALIMENT_M3;
    }

    public void setPARAM_AyO_PLANTA_ALIMENT_M3(String PARAM_AyO_PLANTA_ALIMENT_M3) {
        this.PARAM_AyO_PLANTA_ALIMENT_M3 = PARAM_AyO_PLANTA_ALIMENT_M3;
    }

    public String getPARAM_AyO_PLANTA_ALIMENT_M4() {
        return PARAM_AyO_PLANTA_ALIMENT_M4;
    }

    public void setPARAM_AyO_PLANTA_ALIMENT_M4(String PARAM_AyO_PLANTA_ALIMENT_M4) {
        this.PARAM_AyO_PLANTA_ALIMENT_M4 = PARAM_AyO_PLANTA_ALIMENT_M4;
    }

    public String getPARAM_AyO_PLANTA_ALIMENT_M5() {
        return PARAM_AyO_PLANTA_ALIMENT_M5;
    }

    public void setPARAM_AyO_PLANTA_ALIMENT_M5(String PARAM_AyO_PLANTA_ALIMENT_M5) {
        this.PARAM_AyO_PLANTA_ALIMENT_M5 = PARAM_AyO_PLANTA_ALIMENT_M5;
    }

    public String getPARAM_AyO_PLANTA_ALIMENT_M6() {
        return PARAM_AyO_PLANTA_ALIMENT_M6;
    }

    public void setPARAM_AyO_PLANTA_ALIMENT_M6(String PARAM_AyO_PLANTA_ALIMENT_M6) {
        this.PARAM_AyO_PLANTA_ALIMENT_M6 = PARAM_AyO_PLANTA_ALIMENT_M6;
    }

    public String getPARAM_AyO_PLANTA_ALIMENT_M7() {
        return PARAM_AyO_PLANTA_ALIMENT_M7;
    }

    public void setPARAM_AyO_PLANTA_ALIMENT_M7(String PARAM_AyO_PLANTA_ALIMENT_M7) {
        this.PARAM_AyO_PLANTA_ALIMENT_M7 = PARAM_AyO_PLANTA_ALIMENT_M7;
    }

    public String getPARAM_AyO_PLANTA_ALIMENT_M8() {
        return PARAM_AyO_PLANTA_ALIMENT_M8;
    }

    public void setPARAM_AyO_PLANTA_ALIMENT_M8(String PARAM_AyO_PLANTA_ALIMENT_M8) {
        this.PARAM_AyO_PLANTA_ALIMENT_M8 = PARAM_AyO_PLANTA_ALIMENT_M8;
    }

    public String getPARAM_AyO_PLANTA_OPERAC_M1() {
        return PARAM_AyO_PLANTA_OPERAC_M1;
    }

    public void setPARAM_AyO_PLANTA_OPERAC_M1(String PARAM_AyO_PLANTA_OPERAC_M1) {
        this.PARAM_AyO_PLANTA_OPERAC_M1 = PARAM_AyO_PLANTA_OPERAC_M1;
    }

    public String getPARAM_AyO_PLANTA_OPERAC_M2() {
        return PARAM_AyO_PLANTA_OPERAC_M2;
    }

    public void setPARAM_AyO_PLANTA_OPERAC_M2(String PARAM_AyO_PLANTA_OPERAC_M2) {
        this.PARAM_AyO_PLANTA_OPERAC_M2 = PARAM_AyO_PLANTA_OPERAC_M2;
    }

    public String getPARAM_AyO_PLANTA_OPERAC_M3() {
        return PARAM_AyO_PLANTA_OPERAC_M3;
    }

    public void setPARAM_AyO_PLANTA_OPERAC_M3(String PARAM_AyO_PLANTA_OPERAC_M3) {
        this.PARAM_AyO_PLANTA_OPERAC_M3 = PARAM_AyO_PLANTA_OPERAC_M3;
    }

    public String getPARAM_AyO_PLANTA_OPERAC_M4() {
        return PARAM_AyO_PLANTA_OPERAC_M4;
    }

    public void setPARAM_AyO_PLANTA_OPERAC_M4(String PARAM_AyO_PLANTA_OPERAC_M4) {
        this.PARAM_AyO_PLANTA_OPERAC_M4 = PARAM_AyO_PLANTA_OPERAC_M4;
    }

    public String getPARAM_AyO_PLANTA_OPERAC_M5() {
        return PARAM_AyO_PLANTA_OPERAC_M5;
    }

    public void setPARAM_AyO_PLANTA_OPERAC_M5(String PARAM_AyO_PLANTA_OPERAC_M5) {
        this.PARAM_AyO_PLANTA_OPERAC_M5 = PARAM_AyO_PLANTA_OPERAC_M5;
    }

    public String getPARAM_AyO_PLANTA_OPERAC_M6() {
        return PARAM_AyO_PLANTA_OPERAC_M6;
    }

    public void setPARAM_AyO_PLANTA_OPERAC_M6(String PARAM_AyO_PLANTA_OPERAC_M6) {
        this.PARAM_AyO_PLANTA_OPERAC_M6 = PARAM_AyO_PLANTA_OPERAC_M6;
    }

    public String getPARAM_AyO_PLANTA_OPERAC_M7() {
        return PARAM_AyO_PLANTA_OPERAC_M7;
    }

    public void setPARAM_AyO_PLANTA_OPERAC_M7(String PARAM_AyO_PLANTA_OPERAC_M7) {
        this.PARAM_AyO_PLANTA_OPERAC_M7 = PARAM_AyO_PLANTA_OPERAC_M7;
    }

    public String getPARAM_AyO_PLANTA_OPERAC_M8() {
        return PARAM_AyO_PLANTA_OPERAC_M8;
    }

    public void setPARAM_AyO_PLANTA_OPERAC_M8(String PARAM_AyO_PLANTA_OPERAC_M8) {
        this.PARAM_AyO_PLANTA_OPERAC_M8 = PARAM_AyO_PLANTA_OPERAC_M8;
    }

    public String getPARAM_AyO_PLANTA_OPERAC_M9() {
        return PARAM_AyO_PLANTA_OPERAC_M9;
    }

    public void setPARAM_AyO_PLANTA_OPERAC_M9(String PARAM_AyO_PLANTA_OPERAC_M9) {
        this.PARAM_AyO_PLANTA_OPERAC_M9 = PARAM_AyO_PLANTA_OPERAC_M9;
    }

    public String getPARAM_AyO_PLANTA_OPERAC_M10() {
        return PARAM_AyO_PLANTA_OPERAC_M10;
    }

    public void setPARAM_AyO_PLANTA_OPERAC_M10(String PARAM_AyO_PLANTA_OPERAC_M10) {
        this.PARAM_AyO_PLANTA_OPERAC_M10 = PARAM_AyO_PLANTA_OPERAC_M10;
    }

    public String getPARAM_AyO_PLANTA_LIMPIEZA_INTERNA() {
        return PARAM_AyO_PLANTA_LIMPIEZA_INTERNA;
    }

    public void setPARAM_AyO_PLANTA_LIMPIEZA_INTERNA(String PARAM_AyO_PLANTA_LIMPIEZA_INTERNA) {
        this.PARAM_AyO_PLANTA_LIMPIEZA_INTERNA = PARAM_AyO_PLANTA_LIMPIEZA_INTERNA;
    }

    public String getPARAM_AyO_PLANTA_LIMPIEZA_INDV() {
        return PARAM_AyO_PLANTA_LIMPIEZA_INDV;
    }

    public void setPARAM_AyO_PLANTA_LIMPIEZA_INDV(String PARAM_AyO_PLANTA_LIMPIEZA_INDV) {
        this.PARAM_AyO_PLANTA_LIMPIEZA_INDV = PARAM_AyO_PLANTA_LIMPIEZA_INDV;
    }

    public String getPARAM_AyO_PLANTA_VERIFICAION() {
        return PARAM_AyO_PLANTA_VERIFICAION;
    }

    public void setPARAM_AyO_PLANTA_VERIFICAION(String PARAM_AyO_PLANTA_VERIFICAION) {
        this.PARAM_AyO_PLANTA_VERIFICAION = PARAM_AyO_PLANTA_VERIFICAION;
    }

    public String getPARAM_STPF_DC_NA() {
        return PARAM_STPF_DC_NA;
    }

    public void setPARAM_STPF_DC_NA(String PARAM_STPF_DC_NA) {
        this.PARAM_STPF_DC_NA = PARAM_STPF_DC_NA;
    }

    public String getPARAM_STPF_DC_CAMP1() {
        return PARAM_STPF_DC_CAMP1;
    }

    public void setPARAM_STPF_DC_CAMP1(String PARAM_STPF_DC_CAMP1) {
        this.PARAM_STPF_DC_CAMP1 = PARAM_STPF_DC_CAMP1;
    }

    public String getPARAM_STPF_DC_CAMP2() {
        return PARAM_STPF_DC_CAMP2;
    }

    public void setPARAM_STPF_DC_CAMP2(String PARAM_STPF_DC_CAMP2) {
        this.PARAM_STPF_DC_CAMP2 = PARAM_STPF_DC_CAMP2;
    }

    public String getPARAM_STPF_DC_CAMP3() {
        return PARAM_STPF_DC_CAMP3;
    }

    public void setPARAM_STPF_DC_CAMP3(String PARAM_STPF_DC_CAMP3) {
        this.PARAM_STPF_DC_CAMP3 = PARAM_STPF_DC_CAMP3;
    }

    public String getPARAM_STPF_DC_CAMP4() {
        return PARAM_STPF_DC_CAMP4;
    }

    public void setPARAM_STPF_DC_CAMP4(String PARAM_STPF_DC_CAMP4) {
        this.PARAM_STPF_DC_CAMP4 = PARAM_STPF_DC_CAMP4;
    }

    public String getPARAM_STPF_DC_CAMP5() {
        return PARAM_STPF_DC_CAMP5;
    }

    public void setPARAM_STPF_DC_CAMP5(String PARAM_STPF_DC_CAMP5) {
        this.PARAM_STPF_DC_CAMP5 = PARAM_STPF_DC_CAMP5;
    }

    public String getPARAM_STPF_DC_CAMP6() {
        return PARAM_STPF_DC_CAMP6;
    }

    public void setPARAM_STPF_DC_CAMP6(String PARAM_STPF_DC_CAMP6) {
        this.PARAM_STPF_DC_CAMP6 = PARAM_STPF_DC_CAMP6;
    }

    public String getPARAM_STPF_DC_CAMP7() {
        return PARAM_STPF_DC_CAMP7;
    }

    public void setPARAM_STPF_DC_CAMP7(String PARAM_STPF_DC_CAMP7) {
        this.PARAM_STPF_DC_CAMP7 = PARAM_STPF_DC_CAMP7;
    }

    public String getPARAM_STPF_DC_CAMP8() {
        return PARAM_STPF_DC_CAMP8;
    }

    public void setPARAM_STPF_DC_CAMP8(String PARAM_STPF_DC_CAMP8) {
        this.PARAM_STPF_DC_CAMP8 = PARAM_STPF_DC_CAMP8;
    }

    public String getPARAM_ITPF_DC_NA() {
        return PARAM_ITPF_DC_NA;
    }

    public void setPARAM_ITPF_DC_NA(String PARAM_ITPF_DC_NA) {
        this.PARAM_ITPF_DC_NA = PARAM_ITPF_DC_NA;
    }

    public String getPARAM_ITPF_DC_CAMP1() {
        return PARAM_ITPF_DC_CAMP1;
    }

    public void setPARAM_ITPF_DC_CAMP1(String PARAM_ITPF_DC_CAMP1) {
        this.PARAM_ITPF_DC_CAMP1 = PARAM_ITPF_DC_CAMP1;
    }

    public String getPARAM_ITPF_DC_CAMP2() {
        return PARAM_ITPF_DC_CAMP2;
    }

    public void setPARAM_ITPF_DC_CAMP2(String PARAM_ITPF_DC_CAMP2) {
        this.PARAM_ITPF_DC_CAMP2 = PARAM_ITPF_DC_CAMP2;
    }

    public String getPARAM_ITPF_DC_CAMP3() {
        return PARAM_ITPF_DC_CAMP3;
    }

    public void setPARAM_ITPF_DC_CAMP3(String PARAM_ITPF_DC_CAMP3) {
        this.PARAM_ITPF_DC_CAMP3 = PARAM_ITPF_DC_CAMP3;
    }

    public String getPARAM_ITPF_DC_CAMP4() {
        return PARAM_ITPF_DC_CAMP4;
    }

    public void setPARAM_ITPF_DC_CAMP4(String PARAM_ITPF_DC_CAMP4) {
        this.PARAM_ITPF_DC_CAMP4 = PARAM_ITPF_DC_CAMP4;
    }

    public String getPARAM_ITPF_DC_CAMP5() {
        return PARAM_ITPF_DC_CAMP5;
    }

    public void setPARAM_ITPF_DC_CAMP5(String PARAM_ITPF_DC_CAMP5) {
        this.PARAM_ITPF_DC_CAMP5 = PARAM_ITPF_DC_CAMP5;
    }

    public String getPARAM_ITPF_DC_CAMP6() {
        return PARAM_ITPF_DC_CAMP6;
    }

    public void setPARAM_ITPF_DC_CAMP6(String PARAM_ITPF_DC_CAMP6) {
        this.PARAM_ITPF_DC_CAMP6 = PARAM_ITPF_DC_CAMP6;
    }

    public String getPARAM_ITPF_DC_CAMP7() {
        return PARAM_ITPF_DC_CAMP7;
    }

    public void setPARAM_ITPF_DC_CAMP7(String PARAM_ITPF_DC_CAMP7) {
        this.PARAM_ITPF_DC_CAMP7 = PARAM_ITPF_DC_CAMP7;
    }

    public String getPARAM_SISTEMA_DIST_NA() {
        return PARAM_SISTEMA_DIST_NA;
    }

    public void setPARAM_SISTEMA_DIST_NA(String PARAM_SISTEMA_DIST_NA) {
        this.PARAM_SISTEMA_DIST_NA = PARAM_SISTEMA_DIST_NA;
    }

    public String getPARAM_SISTEMA_DIST_MODELO() {
        return PARAM_SISTEMA_DIST_MODELO;
    }

    public void setPARAM_SISTEMA_DIST_MODELO(String PARAM_SISTEMA_DIST_MODELO) {
        this.PARAM_SISTEMA_DIST_MODELO = PARAM_SISTEMA_DIST_MODELO;
    }

    public String getPARAM_SISTEMA_DIST_MARCA() {
        return PARAM_SISTEMA_DIST_MARCA;
    }

    public void setPARAM_SISTEMA_DIST_MARCA(String PARAM_SISTEMA_DIST_MARCA) {
        this.PARAM_SISTEMA_DIST_MARCA = PARAM_SISTEMA_DIST_MARCA;
    }

    public String getPARAM_SISTEMA_DIST_ESPECIFI() {
        return PARAM_SISTEMA_DIST_ESPECIFI;
    }

    public void setPARAM_SISTEMA_DIST_ESPECIFI(String PARAM_SISTEMA_DIST_ESPECIFI) {
        this.PARAM_SISTEMA_DIST_ESPECIFI = PARAM_SISTEMA_DIST_ESPECIFI;
    }

    public String getPARAM_SISTEMA_DIST_CAPACIDAD() {
        return PARAM_SISTEMA_DIST_CAPACIDAD;
    }

    public void setPARAM_SISTEMA_DIST_CAPACIDAD(String PARAM_SISTEMA_DIST_CAPACIDAD) {
        this.PARAM_SISTEMA_DIST_CAPACIDAD = PARAM_SISTEMA_DIST_CAPACIDAD;
    }

    public String getPARAM_SISTEMA_DIST_CONFIGURACION() {
        return PARAM_SISTEMA_DIST_CONFIGURACION;
    }

    public void setPARAM_SISTEMA_DIST_CONFIGURACION(String PARAM_SISTEMA_DIST_CONFIGURACION) {
        this.PARAM_SISTEMA_DIST_CONFIGURACION = PARAM_SISTEMA_DIST_CONFIGURACION;
    }

    public String getPARAM_IDR_NA() {
        return PARAM_IDR_NA;
    }

    public void setPARAM_IDR_NA(String PARAM_IDR_NA) {
        this.PARAM_IDR_NA = PARAM_IDR_NA;
    }

    public String getPARAM_IDR_CAMP1() {
        return PARAM_IDR_CAMP1;
    }

    public void setPARAM_IDR_CAMP1(String PARAM_IDR_CAMP1) {
        this.PARAM_IDR_CAMP1 = PARAM_IDR_CAMP1;
    }

    public String getPARAM_IDR_CAMP2() {
        return PARAM_IDR_CAMP2;
    }

    public void setPARAM_IDR_CAMP2(String PARAM_IDR_CAMP2) {
        this.PARAM_IDR_CAMP2 = PARAM_IDR_CAMP2;
    }

    public String getPARAM_IDR_CAMP3() {
        return PARAM_IDR_CAMP3;
    }

    public void setPARAM_IDR_CAMP3(String PARAM_IDR_CAMP3) {
        this.PARAM_IDR_CAMP3 = PARAM_IDR_CAMP3;
    }

    public String getPARAM_IDR_CAMP4() {
        return PARAM_IDR_CAMP4;
    }

    public void setPARAM_IDR_CAMP4(String PARAM_IDR_CAMP4) {
        this.PARAM_IDR_CAMP4 = PARAM_IDR_CAMP4;
    }

    public String getPARAM_IDR_CAMP5() {
        return PARAM_IDR_CAMP5;
    }

    public void setPARAM_IDR_CAMP5(String PARAM_IDR_CAMP5) {
        this.PARAM_IDR_CAMP5 = PARAM_IDR_CAMP5;
    }

    public String getPARAM_IDR_CAMP6() {
        return PARAM_IDR_CAMP6;
    }

    public void setPARAM_IDR_CAMP6(String PARAM_IDR_CAMP6) {
        this.PARAM_IDR_CAMP6 = PARAM_IDR_CAMP6;
    }

    public String getPARAM_IDR_CAMP7() {
        return PARAM_IDR_CAMP7;
    }

    public void setPARAM_IDR_CAMP7(String PARAM_IDR_CAMP7) {
        this.PARAM_IDR_CAMP7 = PARAM_IDR_CAMP7;
    }

    public String getPARAM_IDR_BREAK1() {
        return PARAM_IDR_BREAK1;
    }

    public void setPARAM_IDR_BREAK1(String PARAM_IDR_BREAK1) {
        this.PARAM_IDR_BREAK1 = PARAM_IDR_BREAK1;
    }

    public String getPARAM_IDR_BREAK2() {
        return PARAM_IDR_BREAK2;
    }

    public void setPARAM_IDR_BREAK2(String PARAM_IDR_BREAK2) {
        this.PARAM_IDR_BREAK2 = PARAM_IDR_BREAK2;
    }

    public String getPARAM_IDR_BREAK3() {
        return PARAM_IDR_BREAK3;
    }

    public void setPARAM_IDR_BREAK3(String PARAM_IDR_BREAK3) {
        this.PARAM_IDR_BREAK3 = PARAM_IDR_BREAK3;
    }

    public String getPARAM_IDR_BREAK4() {
        return PARAM_IDR_BREAK4;
    }

    public void setPARAM_IDR_BREAK4(String PARAM_IDR_BREAK4) {
        this.PARAM_IDR_BREAK4 = PARAM_IDR_BREAK4;
    }

    public String getPARAM_IDR_BREAK5() {
        return PARAM_IDR_BREAK5;
    }

    public void setPARAM_IDR_BREAK5(String PARAM_IDR_BREAK5) {
        this.PARAM_IDR_BREAK5 = PARAM_IDR_BREAK5;
    }

    public String getPARAM_IDR_BREAK6() {
        return PARAM_IDR_BREAK6;
    }

    public void setPARAM_IDR_BREAK6(String PARAM_IDR_BREAK6) {
        this.PARAM_IDR_BREAK6 = PARAM_IDR_BREAK6;
    }

    public String getPARAM_IDR_BREAK7() {
        return PARAM_IDR_BREAK7;
    }

    public void setPARAM_IDR_BREAK7(String PARAM_IDR_BREAK7) {
        this.PARAM_IDR_BREAK7 = PARAM_IDR_BREAK7;
    }

    public String getPARAM_IDR_BREAK8() {
        return PARAM_IDR_BREAK8;
    }

    public void setPARAM_IDR_BREAK8(String PARAM_IDR_BREAK8) {
        this.PARAM_IDR_BREAK8 = PARAM_IDR_BREAK8;
    }

    public String getPARAM_SISTEMA_INVER_NA() {
        return PARAM_SISTEMA_INVER_NA;
    }

    public void setPARAM_SISTEMA_INVER_NA(String PARAM_SISTEMA_INVER_NA) {
        this.PARAM_SISTEMA_INVER_NA = PARAM_SISTEMA_INVER_NA;
    }

    public String getPARAM_SISTEMA_INVER_MODELO() {
        return PARAM_SISTEMA_INVER_MODELO;
    }

    public void setPARAM_SISTEMA_INVER_MODELO(String PARAM_SISTEMA_INVER_MODELO) {
        this.PARAM_SISTEMA_INVER_MODELO = PARAM_SISTEMA_INVER_MODELO;
    }

    public String getPARAM_SISTEMA_INVER_MARCA() {
        return PARAM_SISTEMA_INVER_MARCA;
    }

    public void setPARAM_SISTEMA_INVER_MARCA(String PARAM_SISTEMA_INVER_MARCA) {
        this.PARAM_SISTEMA_INVER_MARCA = PARAM_SISTEMA_INVER_MARCA;
    }

    public String getPARAM_SISTEMA_INVER_ESPEC() {
        return PARAM_SISTEMA_INVER_ESPEC;
    }

    public void setPARAM_SISTEMA_INVER_ESPEC(String PARAM_SISTEMA_INVER_ESPEC) {
        this.PARAM_SISTEMA_INVER_ESPEC = PARAM_SISTEMA_INVER_ESPEC;
    }

    public String getPARAM_SISTEMA_INVER_CAPACIDAD() {
        return PARAM_SISTEMA_INVER_CAPACIDAD;
    }

    public void setPARAM_SISTEMA_INVER_CAPACIDAD(String PARAM_SISTEMA_INVER_CAPACIDAD) {
        this.PARAM_SISTEMA_INVER_CAPACIDAD = PARAM_SISTEMA_INVER_CAPACIDAD;
    }

    public String getPARAM_SISTEMA_INVER_CONFG() {
        return PARAM_SISTEMA_INVER_CONFG;
    }

    public void setPARAM_SISTEMA_INVER_CONFG(String PARAM_SISTEMA_INVER_CONFG) {
        this.PARAM_SISTEMA_INVER_CONFG = PARAM_SISTEMA_INVER_CONFG;
    }

    public String getPARAM_SISTEMA_INVER_A_PIEZA() {
        return PARAM_SISTEMA_INVER_A_PIEZA;
    }

    public void setPARAM_SISTEMA_INVER_A_PIEZA(String PARAM_SISTEMA_INVER_A_PIEZA) {
        this.PARAM_SISTEMA_INVER_A_PIEZA = PARAM_SISTEMA_INVER_A_PIEZA;
    }

    public String getPARAM_SISTEMA_INVER_A_INV1() {
        return PARAM_SISTEMA_INVER_A_INV1;
    }

    public void setPARAM_SISTEMA_INVER_A_INV1(String PARAM_SISTEMA_INVER_A_INV1) {
        this.PARAM_SISTEMA_INVER_A_INV1 = PARAM_SISTEMA_INVER_A_INV1;
    }

    public String getPARAM_SISTEMA_INVER_A_INV2() {
        return PARAM_SISTEMA_INVER_A_INV2;
    }

    public void setPARAM_SISTEMA_INVER_A_INV2(String PARAM_SISTEMA_INVER_A_INV2) {
        this.PARAM_SISTEMA_INVER_A_INV2 = PARAM_SISTEMA_INVER_A_INV2;
    }

    public String getPARAM_SISTEMA_INVER_A_INV3() {
        return PARAM_SISTEMA_INVER_A_INV3;
    }

    public void setPARAM_SISTEMA_INVER_A_INV3(String PARAM_SISTEMA_INVER_A_INV3) {
        this.PARAM_SISTEMA_INVER_A_INV3 = PARAM_SISTEMA_INVER_A_INV3;
    }

    public String getPARAM_SISTEMA_INVER_A_INV4() {
        return PARAM_SISTEMA_INVER_A_INV4;
    }

    public void setPARAM_SISTEMA_INVER_A_INV4(String PARAM_SISTEMA_INVER_A_INV4) {
        this.PARAM_SISTEMA_INVER_A_INV4 = PARAM_SISTEMA_INVER_A_INV4;
    }

    public String getPARAM_SISTEMA_INVER_A_INV5() {
        return PARAM_SISTEMA_INVER_A_INV5;
    }

    public void setPARAM_SISTEMA_INVER_A_INV5(String PARAM_SISTEMA_INVER_A_INV5) {
        this.PARAM_SISTEMA_INVER_A_INV5 = PARAM_SISTEMA_INVER_A_INV5;
    }

    public String getPARAM_SISTEMA_INVER_A_INV6() {
        return PARAM_SISTEMA_INVER_A_INV6;
    }

    public void setPARAM_SISTEMA_INVER_A_INV6(String PARAM_SISTEMA_INVER_A_INV6) {
        this.PARAM_SISTEMA_INVER_A_INV6 = PARAM_SISTEMA_INVER_A_INV6;
    }

    public String getPARAM_SISTEMA_INVER_A_INV7() {
        return PARAM_SISTEMA_INVER_A_INV7;
    }

    public void setPARAM_SISTEMA_INVER_A_INV7(String PARAM_SISTEMA_INVER_A_INV7) {
        this.PARAM_SISTEMA_INVER_A_INV7 = PARAM_SISTEMA_INVER_A_INV7;
    }

    public String getPARAM_SISTEMA_INVER_A_INV8() {
        return PARAM_SISTEMA_INVER_A_INV8;
    }

    public void setPARAM_SISTEMA_INVER_A_INV8(String PARAM_SISTEMA_INVER_A_INV8) {
        this.PARAM_SISTEMA_INVER_A_INV8 = PARAM_SISTEMA_INVER_A_INV8;
    }

    public String getPARAM_SISTEMA_INVER_A_INV9() {
        return PARAM_SISTEMA_INVER_A_INV9;
    }

    public void setPARAM_SISTEMA_INVER_A_INV9(String PARAM_SISTEMA_INVER_A_INV9) {
        this.PARAM_SISTEMA_INVER_A_INV9 = PARAM_SISTEMA_INVER_A_INV9;
    }

    public String getPARAM_SISTEMA_INVER_A_INV10() {
        return PARAM_SISTEMA_INVER_A_INV10;
    }

    public void setPARAM_SISTEMA_INVER_A_INV10(String PARAM_SISTEMA_INVER_A_INV10) {
        this.PARAM_SISTEMA_INVER_A_INV10 = PARAM_SISTEMA_INVER_A_INV10;
    }

    public String getPARAM_SISTEMA_INVER_B_PIEZA() {
        return PARAM_SISTEMA_INVER_B_PIEZA;
    }

    public void setPARAM_SISTEMA_INVER_B_PIEZA(String PARAM_SISTEMA_INVER_B_PIEZA) {
        this.PARAM_SISTEMA_INVER_B_PIEZA = PARAM_SISTEMA_INVER_B_PIEZA;
    }

    public String getPARAM_SISTEMA_INVER_B_INV1() {
        return PARAM_SISTEMA_INVER_B_INV1;
    }

    public void setPARAM_SISTEMA_INVER_B_INV1(String PARAM_SISTEMA_INVER_B_INV1) {
        this.PARAM_SISTEMA_INVER_B_INV1 = PARAM_SISTEMA_INVER_B_INV1;
    }

    public String getPARAM_SISTEMA_INVER_B_INV2() {
        return PARAM_SISTEMA_INVER_B_INV2;
    }

    public void setPARAM_SISTEMA_INVER_B_INV2(String PARAM_SISTEMA_INVER_B_INV2) {
        this.PARAM_SISTEMA_INVER_B_INV2 = PARAM_SISTEMA_INVER_B_INV2;
    }

    public String getPARAM_SISTEMA_INVER_B_INV3() {
        return PARAM_SISTEMA_INVER_B_INV3;
    }

    public void setPARAM_SISTEMA_INVER_B_INV3(String PARAM_SISTEMA_INVER_B_INV3) {
        this.PARAM_SISTEMA_INVER_B_INV3 = PARAM_SISTEMA_INVER_B_INV3;
    }

    public String getPARAM_SISTEMA_INVER_B_INV4() {
        return PARAM_SISTEMA_INVER_B_INV4;
    }

    public void setPARAM_SISTEMA_INVER_B_INV4(String PARAM_SISTEMA_INVER_B_INV4) {
        this.PARAM_SISTEMA_INVER_B_INV4 = PARAM_SISTEMA_INVER_B_INV4;
    }

    public String getPARAM_SISTEMA_INVER_B_INV5() {
        return PARAM_SISTEMA_INVER_B_INV5;
    }

    public void setPARAM_SISTEMA_INVER_B_INV5(String PARAM_SISTEMA_INVER_B_INV5) {
        this.PARAM_SISTEMA_INVER_B_INV5 = PARAM_SISTEMA_INVER_B_INV5;
    }

    public String getPARAM_SISTEMA_INVER_B_INV6() {
        return PARAM_SISTEMA_INVER_B_INV6;
    }

    public void setPARAM_SISTEMA_INVER_B_INV6(String PARAM_SISTEMA_INVER_B_INV6) {
        this.PARAM_SISTEMA_INVER_B_INV6 = PARAM_SISTEMA_INVER_B_INV6;
    }

    public String getPARAM_SISTEMA_INVER_B_INV7() {
        return PARAM_SISTEMA_INVER_B_INV7;
    }

    public void setPARAM_SISTEMA_INVER_B_INV7(String PARAM_SISTEMA_INVER_B_INV7) {
        this.PARAM_SISTEMA_INVER_B_INV7 = PARAM_SISTEMA_INVER_B_INV7;
    }

    public String getPARAM_SISTEMA_INVER_B_INV8() {
        return PARAM_SISTEMA_INVER_B_INV8;
    }

    public void setPARAM_SISTEMA_INVER_B_INV8(String PARAM_SISTEMA_INVER_B_INV8) {
        this.PARAM_SISTEMA_INVER_B_INV8 = PARAM_SISTEMA_INVER_B_INV8;
    }

    public String getPARAM_SISTEMA_INVER_B_INV9() {
        return PARAM_SISTEMA_INVER_B_INV9;
    }

    public void setPARAM_SISTEMA_INVER_B_INV9(String PARAM_SISTEMA_INVER_B_INV9) {
        this.PARAM_SISTEMA_INVER_B_INV9 = PARAM_SISTEMA_INVER_B_INV9;
    }

    public String getPARAM_SISTEMA_INVER_B_INV10() {
        return PARAM_SISTEMA_INVER_B_INV10;
    }

    public void setPARAM_SISTEMA_INVER_B_INV10(String PARAM_SISTEMA_INVER_B_INV10) {
        this.PARAM_SISTEMA_INVER_B_INV10 = PARAM_SISTEMA_INVER_B_INV10;
    }

    public String getPARAM_SISTEMA_INVER_C_PIEZA() {
        return PARAM_SISTEMA_INVER_C_PIEZA;
    }

    public void setPARAM_SISTEMA_INVER_C_PIEZA(String PARAM_SISTEMA_INVER_C_PIEZA) {
        this.PARAM_SISTEMA_INVER_C_PIEZA = PARAM_SISTEMA_INVER_C_PIEZA;
    }

    public String getPARAM_SISTEMA_INVER_C_INV1() {
        return PARAM_SISTEMA_INVER_C_INV1;
    }

    public void setPARAM_SISTEMA_INVER_C_INV1(String PARAM_SISTEMA_INVER_C_INV1) {
        this.PARAM_SISTEMA_INVER_C_INV1 = PARAM_SISTEMA_INVER_C_INV1;
    }

    public String getPARAM_SISTEMA_INVER_C_INV2() {
        return PARAM_SISTEMA_INVER_C_INV2;
    }

    public void setPARAM_SISTEMA_INVER_C_INV2(String PARAM_SISTEMA_INVER_C_INV2) {
        this.PARAM_SISTEMA_INVER_C_INV2 = PARAM_SISTEMA_INVER_C_INV2;
    }

    public String getPARAM_SISTEMA_INVER_C_INV3() {
        return PARAM_SISTEMA_INVER_C_INV3;
    }

    public void setPARAM_SISTEMA_INVER_C_INV3(String PARAM_SISTEMA_INVER_C_INV3) {
        this.PARAM_SISTEMA_INVER_C_INV3 = PARAM_SISTEMA_INVER_C_INV3;
    }

    public String getPARAM_SISTEMA_INVER_C_INV4() {
        return PARAM_SISTEMA_INVER_C_INV4;
    }

    public void setPARAM_SISTEMA_INVER_C_INV4(String PARAM_SISTEMA_INVER_C_INV4) {
        this.PARAM_SISTEMA_INVER_C_INV4 = PARAM_SISTEMA_INVER_C_INV4;
    }

    public String getPARAM_SISTEMA_INVER_C_INV5() {
        return PARAM_SISTEMA_INVER_C_INV5;
    }

    public void setPARAM_SISTEMA_INVER_C_INV5(String PARAM_SISTEMA_INVER_C_INV5) {
        this.PARAM_SISTEMA_INVER_C_INV5 = PARAM_SISTEMA_INVER_C_INV5;
    }

    public String getPARAM_SISTEMA_INVER_C_INV6() {
        return PARAM_SISTEMA_INVER_C_INV6;
    }

    public void setPARAM_SISTEMA_INVER_C_INV6(String PARAM_SISTEMA_INVER_C_INV6) {
        this.PARAM_SISTEMA_INVER_C_INV6 = PARAM_SISTEMA_INVER_C_INV6;
    }

    public String getPARAM_SISTEMA_INVER_C_INV7() {
        return PARAM_SISTEMA_INVER_C_INV7;
    }

    public void setPARAM_SISTEMA_INVER_C_INV7(String PARAM_SISTEMA_INVER_C_INV7) {
        this.PARAM_SISTEMA_INVER_C_INV7 = PARAM_SISTEMA_INVER_C_INV7;
    }

    public String getPARAM_SISTEMA_INVER_C_INV8() {
        return PARAM_SISTEMA_INVER_C_INV8;
    }

    public void setPARAM_SISTEMA_INVER_C_INV8(String PARAM_SISTEMA_INVER_C_INV8) {
        this.PARAM_SISTEMA_INVER_C_INV8 = PARAM_SISTEMA_INVER_C_INV8;
    }

    public String getPARAM_SISTEMA_INVER_C_INV9() {
        return PARAM_SISTEMA_INVER_C_INV9;
    }

    public void setPARAM_SISTEMA_INVER_C_INV9(String PARAM_SISTEMA_INVER_C_INV9) {
        this.PARAM_SISTEMA_INVER_C_INV9 = PARAM_SISTEMA_INVER_C_INV9;
    }

    public String getPARAM_SISTEMA_INVER_C_INV10() {
        return PARAM_SISTEMA_INVER_C_INV10;
    }

    public void setPARAM_SISTEMA_INVER_C_INV10(String PARAM_SISTEMA_INVER_C_INV10) {
        this.PARAM_SISTEMA_INVER_C_INV10 = PARAM_SISTEMA_INVER_C_INV10;
    }

    public String getPARAM_SISTEMA_INVER_VERI1() {
        return PARAM_SISTEMA_INVER_VERI1;
    }

    public void setPARAM_SISTEMA_INVER_VERI1(String PARAM_SISTEMA_INVER_VERI1) {
        this.PARAM_SISTEMA_INVER_VERI1 = PARAM_SISTEMA_INVER_VERI1;
    }

    public String getPARAM_SISTEMA_INVER_VERI2() {
        return PARAM_SISTEMA_INVER_VERI2;
    }

    public void setPARAM_SISTEMA_INVER_VERI2(String PARAM_SISTEMA_INVER_VERI2) {
        this.PARAM_SISTEMA_INVER_VERI2 = PARAM_SISTEMA_INVER_VERI2;
    }

    public String getPARAM_SISTEMA_INVER_VERI3() {
        return PARAM_SISTEMA_INVER_VERI3;
    }

    public void setPARAM_SISTEMA_INVER_VERI3(String PARAM_SISTEMA_INVER_VERI3) {
        this.PARAM_SISTEMA_INVER_VERI3 = PARAM_SISTEMA_INVER_VERI3;
    }

    public String getPARAM_SISTEMA_INVER_VERI4() {
        return PARAM_SISTEMA_INVER_VERI4;
    }

    public void setPARAM_SISTEMA_INVER_VERI4(String PARAM_SISTEMA_INVER_VERI4) {
        this.PARAM_SISTEMA_INVER_VERI4 = PARAM_SISTEMA_INVER_VERI4;
    }

    public String getPARAM_SISTEMA_INVER_LIMP() {
        return PARAM_SISTEMA_INVER_LIMP;
    }

    public void setPARAM_SISTEMA_INVER_LIMP(String PARAM_SISTEMA_INVER_LIMP) {
        this.PARAM_SISTEMA_INVER_LIMP = PARAM_SISTEMA_INVER_LIMP;
    }

    public String getPARAM_NAyS_ALIM_VAC1() {
        return PARAM_NAyS_ALIM_VAC1;
    }

    public void setPARAM_NAyS_ALIM_VAC1(String PARAM_NAyS_ALIM_VAC1) {
        this.PARAM_NAyS_ALIM_VAC1 = PARAM_NAyS_ALIM_VAC1;
    }

    public String getPARAM_NAyS_ALIM_VAC2() {
        return PARAM_NAyS_ALIM_VAC2;
    }

    public void setPARAM_NAyS_ALIM_VAC2(String PARAM_NAyS_ALIM_VAC2) {
        this.PARAM_NAyS_ALIM_VAC2 = PARAM_NAyS_ALIM_VAC2;
    }

    public String getPARAM_NAyS_ALIM_VAC3() {
        return PARAM_NAyS_ALIM_VAC3;
    }

    public void setPARAM_NAyS_ALIM_VAC3(String PARAM_NAyS_ALIM_VAC3) {
        this.PARAM_NAyS_ALIM_VAC3 = PARAM_NAyS_ALIM_VAC3;
    }

    public String getPARAM_NAyS_ALIM_VAC4() {
        return PARAM_NAyS_ALIM_VAC4;
    }

    public void setPARAM_NAyS_ALIM_VAC4(String PARAM_NAyS_ALIM_VAC4) {
        this.PARAM_NAyS_ALIM_VAC4 = PARAM_NAyS_ALIM_VAC4;
    }

    public String getPARAM_NAyS_ALIM_VAC5() {
        return PARAM_NAyS_ALIM_VAC5;
    }

    public void setPARAM_NAyS_ALIM_VAC5(String PARAM_NAyS_ALIM_VAC5) {
        this.PARAM_NAyS_ALIM_VAC5 = PARAM_NAyS_ALIM_VAC5;
    }

    public String getPARAM_NAyS_ALIM_VAC6() {
        return PARAM_NAyS_ALIM_VAC6;
    }

    public void setPARAM_NAyS_ALIM_VAC6(String PARAM_NAyS_ALIM_VAC6) {
        this.PARAM_NAyS_ALIM_VAC6 = PARAM_NAyS_ALIM_VAC6;
    }

    public String getPARAM_NAyS_ALIM_VAC7() {
        return PARAM_NAyS_ALIM_VAC7;
    }

    public void setPARAM_NAyS_ALIM_VAC7(String PARAM_NAyS_ALIM_VAC7) {
        this.PARAM_NAyS_ALIM_VAC7 = PARAM_NAyS_ALIM_VAC7;
    }

    public String getPARAM_NAyS_ALIM_VAC8() {
        return PARAM_NAyS_ALIM_VAC8;
    }

    public void setPARAM_NAyS_ALIM_VAC8(String PARAM_NAyS_ALIM_VAC8) {
        this.PARAM_NAyS_ALIM_VAC8 = PARAM_NAyS_ALIM_VAC8;
    }

    public String getPARAM_NAyS_ALIM_ACA1() {
        return PARAM_NAyS_ALIM_ACA1;
    }

    public void setPARAM_NAyS_ALIM_ACA1(String PARAM_NAyS_ALIM_ACA1) {
        this.PARAM_NAyS_ALIM_ACA1 = PARAM_NAyS_ALIM_ACA1;
    }

    public String getPARAM_NAyS_ALIM_ACA2() {
        return PARAM_NAyS_ALIM_ACA2;
    }

    public void setPARAM_NAyS_ALIM_ACA2(String PARAM_NAyS_ALIM_ACA2) {
        this.PARAM_NAyS_ALIM_ACA2 = PARAM_NAyS_ALIM_ACA2;
    }

    public String getPARAM_NAyS_ALIM_ACA3() {
        return PARAM_NAyS_ALIM_ACA3;
    }

    public void setPARAM_NAyS_ALIM_ACA3(String PARAM_NAyS_ALIM_ACA3) {
        this.PARAM_NAyS_ALIM_ACA3 = PARAM_NAyS_ALIM_ACA3;
    }

    public String getPARAM_NAyS_ALIM_ACA4() {
        return PARAM_NAyS_ALIM_ACA4;
    }

    public void setPARAM_NAyS_ALIM_ACA4(String PARAM_NAyS_ALIM_ACA4) {
        this.PARAM_NAyS_ALIM_ACA4 = PARAM_NAyS_ALIM_ACA4;
    }

    public String getPARAM_NAyS_ALIM_ACA5() {
        return PARAM_NAyS_ALIM_ACA5;
    }

    public void setPARAM_NAyS_ALIM_ACA5(String PARAM_NAyS_ALIM_ACA5) {
        this.PARAM_NAyS_ALIM_ACA5 = PARAM_NAyS_ALIM_ACA5;
    }

    public String getPARAM_NAyS_ALIM_ACA6() {
        return PARAM_NAyS_ALIM_ACA6;
    }

    public void setPARAM_NAyS_ALIM_ACA6(String PARAM_NAyS_ALIM_ACA6) {
        this.PARAM_NAyS_ALIM_ACA6 = PARAM_NAyS_ALIM_ACA6;
    }

    public String getPARAM_NAyS_ALIM_ACA7() {
        return PARAM_NAyS_ALIM_ACA7;
    }

    public void setPARAM_NAyS_ALIM_ACA7(String PARAM_NAyS_ALIM_ACA7) {
        this.PARAM_NAyS_ALIM_ACA7 = PARAM_NAyS_ALIM_ACA7;
    }

    public String getPARAM_NAyS_ALIM_ACA8() {
        return PARAM_NAyS_ALIM_ACA8;
    }

    public void setPARAM_NAyS_ALIM_ACA8(String PARAM_NAyS_ALIM_ACA8) {
        this.PARAM_NAyS_ALIM_ACA8 = PARAM_NAyS_ALIM_ACA8;
    }

    public String getPARAM_NAyS_SALID_VAC1() {
        return PARAM_NAyS_SALID_VAC1;
    }

    public void setPARAM_NAyS_SALID_VAC1(String PARAM_NAyS_SALID_VAC1) {
        this.PARAM_NAyS_SALID_VAC1 = PARAM_NAyS_SALID_VAC1;
    }

    public String getPARAM_NAyS_SALID_VAC2() {
        return PARAM_NAyS_SALID_VAC2;
    }

    public void setPARAM_NAyS_SALID_VAC2(String PARAM_NAyS_SALID_VAC2) {
        this.PARAM_NAyS_SALID_VAC2 = PARAM_NAyS_SALID_VAC2;
    }

    public String getPARAM_NAyS_SALID_VAC3() {
        return PARAM_NAyS_SALID_VAC3;
    }

    public void setPARAM_NAyS_SALID_VAC3(String PARAM_NAyS_SALID_VAC3) {
        this.PARAM_NAyS_SALID_VAC3 = PARAM_NAyS_SALID_VAC3;
    }

    public String getPARAM_NAyS_SALID_VAC4() {
        return PARAM_NAyS_SALID_VAC4;
    }

    public void setPARAM_NAyS_SALID_VAC4(String PARAM_NAyS_SALID_VAC4) {
        this.PARAM_NAyS_SALID_VAC4 = PARAM_NAyS_SALID_VAC4;
    }

    public String getPARAM_NAyS_SALID_VAC5() {
        return PARAM_NAyS_SALID_VAC5;
    }

    public void setPARAM_NAyS_SALID_VAC5(String PARAM_NAyS_SALID_VAC5) {
        this.PARAM_NAyS_SALID_VAC5 = PARAM_NAyS_SALID_VAC5;
    }

    public String getPARAM_NAyS_SALID_VAC6() {
        return PARAM_NAyS_SALID_VAC6;
    }

    public void setPARAM_NAyS_SALID_VAC6(String PARAM_NAyS_SALID_VAC6) {
        this.PARAM_NAyS_SALID_VAC6 = PARAM_NAyS_SALID_VAC6;
    }

    public String getPARAM_NAyS_SALID_VAC7() {
        return PARAM_NAyS_SALID_VAC7;
    }

    public void setPARAM_NAyS_SALID_VAC7(String PARAM_NAyS_SALID_VAC7) {
        this.PARAM_NAyS_SALID_VAC7 = PARAM_NAyS_SALID_VAC7;
    }

    public String getPARAM_NAyS_SALID_VAC8() {
        return PARAM_NAyS_SALID_VAC8;
    }

    public void setPARAM_NAyS_SALID_VAC8(String PARAM_NAyS_SALID_VAC8) {
        this.PARAM_NAyS_SALID_VAC8 = PARAM_NAyS_SALID_VAC8;
    }

    public String getPARAM_NAyS_SALID_ACA1() {
        return PARAM_NAyS_SALID_ACA1;
    }

    public void setPARAM_NAyS_SALID_ACA1(String PARAM_NAyS_SALID_ACA1) {
        this.PARAM_NAyS_SALID_ACA1 = PARAM_NAyS_SALID_ACA1;
    }

    public String getPARAM_NAyS_SALID_ACA2() {
        return PARAM_NAyS_SALID_ACA2;
    }

    public void setPARAM_NAyS_SALID_ACA2(String PARAM_NAyS_SALID_ACA2) {
        this.PARAM_NAyS_SALID_ACA2 = PARAM_NAyS_SALID_ACA2;
    }

    public String getPARAM_NAyS_SALID_ACA3() {
        return PARAM_NAyS_SALID_ACA3;
    }

    public void setPARAM_NAyS_SALID_ACA3(String PARAM_NAyS_SALID_ACA3) {
        this.PARAM_NAyS_SALID_ACA3 = PARAM_NAyS_SALID_ACA3;
    }

    public String getPARAM_NAyS_SALID_ACA4() {
        return PARAM_NAyS_SALID_ACA4;
    }

    public void setPARAM_NAyS_SALID_ACA4(String PARAM_NAyS_SALID_ACA4) {
        this.PARAM_NAyS_SALID_ACA4 = PARAM_NAyS_SALID_ACA4;
    }

    public String getPARAM_NAyS_SALID_ACA5() {
        return PARAM_NAyS_SALID_ACA5;
    }

    public void setPARAM_NAyS_SALID_ACA5(String PARAM_NAyS_SALID_ACA5) {
        this.PARAM_NAyS_SALID_ACA5 = PARAM_NAyS_SALID_ACA5;
    }

    public String getPARAM_NAyS_SALID_ACA6() {
        return PARAM_NAyS_SALID_ACA6;
    }

    public void setPARAM_NAyS_SALID_ACA6(String PARAM_NAyS_SALID_ACA6) {
        this.PARAM_NAyS_SALID_ACA6 = PARAM_NAyS_SALID_ACA6;
    }

    public String getPARAM_NAyS_SALID_ACA7() {
        return PARAM_NAyS_SALID_ACA7;
    }

    public void setPARAM_NAyS_SALID_ACA7(String PARAM_NAyS_SALID_ACA7) {
        this.PARAM_NAyS_SALID_ACA7 = PARAM_NAyS_SALID_ACA7;
    }

    public String getPARAM_NAyS_SALID_ACA8() {
        return PARAM_NAyS_SALID_ACA8;
    }

    public void setPARAM_NAyS_SALID_ACA8(String PARAM_NAyS_SALID_ACA8) {
        this.PARAM_NAyS_SALID_ACA8 = PARAM_NAyS_SALID_ACA8;
    }
}